; =============================================================================
; PROJECT:     "Rase" Radio Sensor Project,    ESP32-S3 Station Device Firmware
; COPYRIGHT:   (C)2025-2026 KKS-Elektronik,  M. Kreck, <makreck@googlemail.com>
;
; This program is free software: you can redistribute it and/or modify it under
; the terms of the GNU General Public License as published by the Free Software
; Foundation, either version 3 of the License, or (at your option) any later
; version.
;
; This program is distributed in the hope that it will be useful,   but WITHOUT
; ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
; FOR A PARTICULAR PURPOSE, see the GNU General Public License for details.
;
; You should have received a copy of the  GNU General Public License along with
; this program. If not, see <https://www.gnu.org/licenses/>.
; =============================================================================

[platformio]
; default_envs = seeed_xiao_esp32s3
; default_envs = waveshare_esp32s3_mini
default_envs = esp32-s3-devkitc-1
; default_envs = upesy_wroom
; default_envs = esp32dev


[env]
platform = espressif32
framework = espidf
board_build.partitions = huge_app.csv
debug_init_break = tbreak setup
;upload_port = COM3
;monitor_port = COM3
monitor_speed = 115200
;monitor_filters = colorize
build_flags =
;   -DIDF_PATH="/home/mk/.espressif/v6.0.1/esp-idf"
   -mfix-esp32-psram-cache-strategy=memw
   -D ${sysenv.BUILD_FLAGS}
   -DBOARD_HAS_PSRAM
   -DCONFIG_BT_ENABLED=y
   -DCONFIG_BT_CONTROLLER_ENABLED=y


[env:seeed_xiao_esp32s3]
extends = env
board = seeed_xiao_esp32s3
board_build.mcu = esp32s3
board_build.flash_mode = dio
debug_tool = esp-builtin
board_build.arduino.memory_type = qio_opi
board_build.extra_flags = -DBOARD_HAS_PSRAM
board_upload.flash_size = 8MB   
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
build_flags = 
   -DSEEED_XIAO_S3
   ${env.build_flags}


[env:waveshare_esp32s3_mini]
extends = env
board = adafruit_qtpy_esp32s2
board_build.mcu = esp32s3
debug_tool = esp-builtin
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
build_flags = 
   -DESP32_S3_ZERO
   ${env.build_flags}


[env:esp32-s3-devkitc-1]
extends = env
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
debug_tool = esp-builtin
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
build_flags = 
   -DESP32_S3_WROOM_1
   ${env.build_flags}


[env:upesy_wroom]
extends = env
platform = espressif32
board = upesy_wroom
board_build.mcu = esp32
board_build.f_cpu = 240000000L
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_flags = 
   -DESP32_WROOM_DEV
   ${env.build_flags}


[env:esp32dev]
platform = espressif32
board = esp32dev   
framework = espidf
debug_tool = esp-prog
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_flags = 
   -DESP32_WROVER_DEV
   ${env.build_flags}
