/*
 * ==============================================================================
 *
 *  PROJECT:     "Rase" Radio Sensor Project,    ESP32-S3 Station Device Firmware
 *  COPYRIGHT:   (C)2025-2026 KKS-Elektronik,  M. Kreck, <makreck@googlemail.com>
 *
 *  This program is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation, either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful,   but WITHOUT
 *  ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE, see the GNU General Public License for details.
 *
 *  You should have received a copy of the  GNU General Public License along with
 *  this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * ==============================================================================
 */

#include "includes.hpp"
#include "app.hpp"

const char *WebServer::config_website_resp_str =
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"    <meta charset=\"UTF-8\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
	"    <title>RASE Sensor Configuration</title>\n"
	"    <style>\n"
	"        :root {\n"
	"            --primary: #13579b;\n"
	"            --primary-dark: #0f4788;\n"
	"            --primary-light: #7ac2fd;\n"
	"            --secondary: #4caf50;\n"
	"            --background: #000308;\n"
	"            --surface: #001025;\n"
	"            --text-primary: #ffffff;\n"
	"            --text-secondary: #b0b0b0;\n"
	"            --error: #f44336;\n"
	"            --success: #4caf50;\n"
	"            --warning: #ff9800;\n"
	"        }\n"
	"\n"
	"        * {\n"
	"            margin: 0;\n"
	"            padding: 0;\n"
	"            box-sizing: border-box;\n"
	"            font-family: 'Roboto', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
	"        }\n"
	"\n"
	"        body {\n"
	"            background-color: var(--background);\n"
	"            color: var(--text-primary);\n"
	"            line-height: 1.6;\n"
	"            padding: 20px;\n"
	"        }\n"
	"\n"
	"        .container {\n"
	"            max-width: 1200px;\n"
	"            margin: 0 auto;\n"
	"        }\n"
	"\n"
	"        header {\n"
	"            display: flex;\n"
	"            justify-content: space-between;\n"
	"            align-items: center;\n"
	"            padding: 20px 0;\n"
	"            border-bottom: 1px solid #333;\n"
	"            margin-bottom: 30px;\n"
	"        }\n"
	"\n"
	"        h1 {\n"
	"            font-size: 2rem;\n"
	"            font-weight: 500;\n"
	"            color: var(--primary-light);\n"
	"        }\n"
	"\n"
	"        .logo {\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            gap: 10px;\n"
	"        }\n"
	"\n"
	"        .logo-icon {\n"
	"            background-color: var(--primary);\n"
	"            width: 40px;\n"
	"            height: 40px;\n"
	"            border-radius: 50%;\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            justify-content: center;\n"
	"            font-weight: bold;\n"
	"        }\n"
	"\n"
	"        .card {\n"
	"            background-color: var(--surface);\n"
	"            border-radius: 10px;\n"
	"            padding: 20px;\n"
	"            margin-bottom: 25px;\n"
	"            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n"
	"        }\n"
	"\n"
	"        .card-title {\n"
	"            font-size: 1.3rem;\n"
	"            margin-bottom: 15px;\n"
	"            padding-bottom: 10px;\n"
	"            border-bottom: 1px solid #333;\n"
	"            color: var(--primary-light);\n"
	"        }\n"
	"\n"
	"        .form-group {\n"
	"            margin-bottom: 20px;\n"
	"        }\n"
	"\n"
	"        label {\n"
	"            display: block;\n"
	"            margin-bottom: 8px;\n"
	"            font-weight: 500;\n"
	"        }\n"
	"\n"
	"        input,\n"
	"        select {\n"
	"            width: 100%;\n"
	"            padding: 12px;\n"
	"            background-color: #012f85;\n"
	"            border: 1px solid #444;\n"
	"            border-radius: 4px;\n"
	"            color: var(--text-primary);\n"
	"            font-size: 1rem;\n"
	"        }\n"
	"\n"
	"        input:focus,\n"
	"        select:focus {\n"
	"            outline: none;\n"
	"            border-color: var(--primary);\n"
	"        }\n"
	"\n"
	"        .btn {\n"
	"            background-color: var(--primary);\n"
	"            color: white;\n"
	"            border: none;\n"
	"            padding: 12px 20px;\n"
	"            border-radius: 4px;\n"
	"            cursor: pointer;\n"
	"            font-size: 1rem;\n"
	"            font-weight: 500;\n"
	"            transition: all 0.3s ease;\n"
	"            display: inline-flex;\n"
	"            align-items: center;\n"
	"            gap: 8px;\n"
	"        }\n"
	"\n"
	"        .btn:hover {\n"
	"            background-color: var(--primary-dark);\n"
	"            transform: translateY(-2px);\n"
	"            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
	"        }\n"
	"\n"
	"        .btn-success {\n"
	"            background-color: var(--secondary);\n"
	"        }\n"
	"\n"
	"        .btn-success:hover {\n"
	"            background-color: var(--primary-dark);\n"
	"        }\n"
	"\n"
	"        .btn-block {\n"
	"            display: block;\n"
	"            width: 100%;\n"
	"        }\n"
	"\n"
	"        .btn-group {\n"
	"            display: flex;\n"
	"            gap: 10px;\n"
	"            margin-top: 20px;\n"
	"        }\n"
	"\n"
	"        .status-indicator {\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            gap: 8px;\n"
	"            margin-bottom: 15px;\n"
	"            padding: 10px;\n"
	"            border-radius: 4px;\n"
	"            background-color: var(--primary-dark);\n"
	"        }\n"
	"\n"
	"        .status-dot {\n"
	"            width: 12px;\n"
	"            height: 12px;\n"
	"            border-radius: 50%;\n"
	"            background-color: var(--error);\n"
	"        }\n"
	"\n"
	"        .status-dot.connected {\n"
	"            background-color: var(--success);\n"
	"        }\n"
	"\n"
	"        .status-text {\n"
	"            font-size: 0.9rem;\n"
	"        }\n"
	"\n"
	"        .firmware-upload {\n"
	"            display: flex;\n"
	"            flex-direction: column;\n"
	"            gap: 15px;\n"
	"        }\n"
	"\n"
	"        .file-input-wrapper {\n"
	"            position: relative;\n"
	"            overflow: hidden;\n"
	"            display: inline-block;\n"
	"            width: 100%;\n"
	"        }\n"
	"\n"
	"        .file-input-wrapper input[type=file] {\n"
	"            position: absolute;\n"
	"            left: 0;\n"
	"            top: 0;\n"
	"            opacity: 0;\n"
	"            width: 100%;\n"
	"            height: 100%;\n"
	"            cursor: pointer;\n"
	"        }\n"
	"\n"
	"        .file-input-button {\n"
	"            display: block;\n"
	"            padding: 12px;\n"
	"            background-color: var(--primary-dark);\n"
	"            border: 1px dashed #444;\n"
	"            border-radius: 4px;\n"
	"            text-align: center;\n"
	"            cursor: pointer;\n"
	"            transition: all 0.3s ease;\n"
	"        }\n"
	"\n"
	"        .file-input-button:hover {\n"
	"            background-color: #3a3a3a;\n"
	"            border-color: var(--primary);\n"
	"        }\n"
	"\n"
	"        .file-name {\n"
	"            margin-top: 10px;\n"
	"            font-size: 0.9rem;\n"
	"            color: var(--text-secondary);\n"
	"        }\n"
	"\n"
	"        .progress-container {\n"
	"            width: 100%;\n"
	"            height: 8px;\n"
	"            background-color: #333;\n"
	"            border-radius: 4px;\n"
	"            margin-top: 15px;\n"
	"            overflow: hidden;\n"
	"        }\n"
	"\n"
	"        .progress-bar {\n"
	"            height: 100%;\n"
	"            background-color: var(--primary);\n"
	"            width: 0%;\n"
	"            transition: width 0.3s ease;\n"
	"        }\n"
	"\n"
	"        .notification {\n"
	"            position: fixed;\n"
	"            top: 20px;\n"
	"            right: 20px;\n"
	"            padding: 15px 20px;\n"
	"            border-radius: 4px;\n"
	"            background-color: var(--success);\n"
	"            color: white;\n"
	"            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\n"
	"            transform: translateX(200%);\n"
	"            transition: transform 0.3s ease;\n"
	"            z-index: 1000;\n"
	"        }\n"
	"\n"
	"        .notification.show {\n"
	"            transform: translateX(0);\n"
	"        }\n"
	"\n"
	"        .notification.error {\n"
	"            background-color: var(--error);\n"
	"        }\n"
	"\n"
	"        .notification.warning {\n"
	"            background-color: var(--warning);\n"
	"        }\n"
	"\n"
	"        .section-divider {\n"
	"            height: 1px;\n"
	"            background-color: #333;\n"
	"            margin: 25px 0;\n"
	"        }\n"
	"\n"
	"        @media (max-width: 768px) {\n"
	"            .btn-group {\n"
	"                flex-direction: column;\n"
	"            }\n"
	"\n"
	"            header {\n"
	"                flex-direction: column;\n"
	"                gap: 15px;\n"
	"                text-align: center;\n"
	"            }\n"
	"        }\n"
	"    </style>\n"
	"</head>\n"
	"\n"
	"<body>\n"
	"    <div class=\"container\">\n"
	"        <header>\n"
	"            <h1>RASE Sensor Configuration</h1>\n"
	"            <div class=\"logo\">\n"
	"                <div class=\"logo-icon\">ESP</div>\n"
	"                <div>Device Manager</div>\n"
	"            </div>\n"
	"        </header>\n"
	"\n"
	"        <div class=\"status-indicator\">\n"
	"            <div class=\"status-dot connected\"></div>\n"
	"            <div class=\"status-text\">Connected to RASE Sensor Device</div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\">WiFi Configuration</h2>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"ssid\">Network Name (SSID)</label>\n"
	"                <input type=\"text\" id=\"ssid\" placeholder=\"Enter WiFi SSID\">\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"password\">Password</label>\n"
	"                <input type=\"password\" id=\"password\" placeholder=\"Enter WiFi password\">\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"wifi-channel\">WiFi Channel</label>\n"
	"                <select id=\"wifi-channel\">\n"
	"                    <option value=\"1\">Channel 1</option>\n"
	"                    <option value=\"2\">Channel 2</option>\n"
	"                    <option value=\"3\">Channel 3</option>\n"
	"                    <option value=\"4\">Channel 4</option>\n"
	"                    <option value=\"5\">Channel 5</option>\n"
	"                    <option value=\"6\">Channel 6</option>\n"
	"                    <option value=\"7\">Channel 7</option>\n"
	"                    <option value=\"8\">Channel 8</option>\n"
	"                    <option value=\"9\">Channel 9</option>\n"
	"                    <option value=\"10\">Channel 10</option>\n"
	"                    <option value=\"11\">Channel 11</option>\n"
	"                    <option value=\"12\">Channel 12</option>\n"
	"                    <option value=\"13\">Channel 13</option>\n"
	"                </select>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\">MQTT Configuration</h2>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"mqtt-enable\">MQTT Status</label>\n"
	"                <select id=\"mqtt-enable\">\n"
	"                    <option value=\"enabled\">Enabled</option>\n"
	"                    <option value=\"disabled\">Disabled</option>\n"
	"                </select>\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"mqtt-broker\">Broker Address</label>\n"
	"                <input type=\"text\" id=\"mqtt-broker\" placeholder=\"Enter MQTT broker IP\">\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"mqtt-username\">Username (Optional)</label>\n"
	"                <input type=\"text\" id=\"mqtt-username\" placeholder=\"Enter MQTT username\">\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"mqtt-password\">Password (Optional)</label>\n"
	"                <input type=\"password\" id=\"mqtt-password\" placeholder=\"Enter MQTT password\">\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\">Display Configuration</h2>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"display-layout\">Display Layout</label>\n"
	"                <select id=\"display-layout\">\n"
	"                    <option value=\"Value page\">Value page</option>\n"
	"                    <option value=\"Details page\">Details page</option>\n"
	"                    <option value=\"Info page\">Info page</option>\n"
	"                </select>\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"display-param\">Display Parameter</label>\n"
	"                <input type=\"number\" id=\"display-param\" min=\"0\" max=\"255\" placeholder=\"Enter parameter value (0-255)\">\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"display-rotation\">Display Rotation</label>\n"
	"                <select id=\"display-rotation\">\n"
	"                    <option value=\"0°\">0°</option>\n"
	"                    <option value=\"180°\">180°</option>\n"
	"                </select>\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"display-timeout\">Display Timeout</label>\n"
	"                <select id=\"display-timeout\">\n"
	"                    <option value=\"Never\">Never</option>\n"
	"                    <option value=\"10 s\">10 seconds</option>\n"
	"                    <option value=\"1 min\">1 minute</option>\n"
	"                    <option value=\"5 min\">5 minutes</option>\n"
	"                    <option value=\"15 min\">15 minutes</option>\n"
	"                    <option value=\"30 min\">30 minutes</option>\n"
	"                </select>\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"display-contrast\">Display Contrast</label>\n"
	"                <input type=\"range\" id=\"display-contrast\" min=\"0\" max=\"100\" value=\"50\">\n"
	"                <div style=\"display: flex; justify-content: space-between; margin-top: 5px;\">\n"
	"                    <span>Low</span>\n"
	"                    <span>High</span>\n"
	"                </div>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\">Sensor Configuration</h2>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"sensor-type\">Sensor Type</label>\n"
	"                <select id=\"sensor-type\">\n"
	"                    <option value=\"autoscan\">autoscan</option>\n"
	"                    <option value=\"Null\">Null</option>\n"
	"                    <option value=\"SHT2x\">SHT2x</option>\n"
	"                    <option value=\"SHT3x\">SHT3x</option>\n"
	"                    <option value=\"HTU21d\">HTU21d</option>\n"
	"                    <option value=\"ATHxx\">ATHxx</option>\n"
	"                    <option value=\"HDC1080\">HDC1080</option>\n"
	"                    <option value=\"BMx280\">BMx280</option>\n"
	"                </select>\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"led-intensity\">LED intensity</label>\n"
	"                <input type=\"range\" id=\"led-intensity\" min=\"0\" max=\"100\" value=\"50\">\n"
	"                <div style=\"display: flex; justify-content: space-between; margin-top: 5px;\">\n"
	"                    <span>Low</span>\n"
	"                    <span>High</span>\n"
	"                </div>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"section-divider\"></div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\">Firmware Update</h2>\n"
	"            <div class=\"firmware-upload\">\n"
	"                <div class=\"file-input-wrapper\">\n"
	"                    <div class=\"file-input-button\" id=\"select-file-button\">\n"
	"                        Select Firmware File (.bin)\n"
	"                    </div>\n"
	"                    <input type=\"file\" id=\"firmware-file\" accept=\".bin\">\n"
	"                </div>\n"
	"                <div class=\"file-name\" id=\"file-name\">No file selected</div>\n"
	"                <div class=\"progress-container\">\n"
	"                    <div class=\"progress-bar\" id=\"progress-bar\"></div>\n"
	"                </div>\n"
	"                <button class=\"btn btn-success btn-block\" id=\"update-firmware\">\n"
	"                    Update Firmware\n"
	"                </button>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"btn-group\">\n"
	"            <button class=\"btn btn-success\" id=\"save-config\">\n"
	"                Save Configuration\n"
	"            </button>\n"
	"            <button class=\"btn\" id=\"reset-device\">\n"
	"                Reset Device\n"
	"            </button>\n"
	"        </div>\n"
	"    </div>\n"
	"\n"
	"    <div class=\"notification\" id=\"notification\"></div>\n"
	"\n"
	"    <script>\n"
	"        const ssidInput = document.getElementById('ssid');\n"
	"        const passwordInput = document.getElementById('password');\n"
	"        const wifiChannelSelect = document.getElementById('wifi-channel');\n"
	"        const mqttEnableSelect = document.getElementById('mqtt-enable');\n"
	"        const mqttBrokerInput = document.getElementById('mqtt-broker');\n"
	"        const mqttUsernameInput = document.getElementById('mqtt-username');\n"
	"        const mqttPasswordInput = document.getElementById('mqtt-password');\n"
	"        const displayLayoutSelect = document.getElementById('display-layout');\n"
	"        const displayParamInput = document.getElementById('display-param');\n"
	"        const displayRotationSelect = document.getElementById('display-rotation');\n"
	"        const displayTimeoutSelect = document.getElementById('display-timeout');\n"
	"        const displayContrastSlider = document.getElementById('display-contrast');\n"
	"        const sensorTypeSelect = document.getElementById('sensor-type');\n"
	"        const sensorUnitSelect = document.getElementById('sensor-unit');\n"
	"        const ledIntensitySlider = document.getElementById('led-intensity');\n"
	"        const firmwareFileInput = document.getElementById('firmware-file');\n"
	"        const selectFileButton = document.getElementById('select-file-button');\n"
	"        const fileNameElement = document.getElementById('file-name');\n"
	"        const progressBar = document.getElementById('progress-bar');\n"
	"        const saveConfigBtn = document.getElementById('save-config');\n"
	"        const resetDeviceBtn = document.getElementById('reset-device');\n"
	"        const updateFirmwareBtn = document.getElementById('update-firmware');\n"
	"        const notification = document.getElementById('notification');\n"
	"\n"
	"        function initializeForm() {\n"
	"            setTimeout(() => {\n"
	"                ssidInput.value = \"MyNetwork\";\n"
	"                passwordInput.value = \"password123\";\n"
	"                wifiChannelSelect.value = \"6\";\n"
	"                mqttEnableSelect.value = \"enabled\";\n"
	"                mqttBrokerInput.value = \"192.168.1.100\";\n"
	"                mqttUsernameInput.value = \"\";\n"
	"                mqttPasswordInput.value = \"\";\n"
	"                displayLayoutSelect.value = \"Value page\";\n"
	"                displayParamInput.value = \"128\";\n"
	"                displayRotationSelect.value = \"0°\";\n"
	"                displayTimeoutSelect.value = \"5 min\";\n"
	"                displayContrastSlider.value = \"75\";\n"
	"                sensorTypeSelect.value = \"SHT3x\";\n"
	"                ledIntensitySlider.value = \"60\";\n"
	"            }, 500);\n"
	"        }\n"
	"\n"
	"        selectFileButton.addEventListener('click', () => {\n"
	"            firmwareFileInput.click();\n"
	"        });\n"
	"\n"
	"        firmwareFileInput.addEventListener('change', (e) => {\n"
	"            const file = e.target.files[0];\n"
	"            if (file) {\n"
	"                fileNameElement.textContent = file.name;\n"
	"                fileNameElement.style.color = '#4CAF50';\n"
	"            } else {\n"
	"                fileNameElement.textContent = 'No file selected';\n"
	"                fileNameElement.style.color = '#999';\n"
	"            }\n"
	"        });\n"
	"\n"
	"\n"
	"        updateFirmwareBtn.addEventListener('click', () => {\n"
	"            if (!firmwareFileInput.files[0]) {\n"
	"                showNotification('Please select a firmware file first', 'error');\n"
	"                return;\n"
	"            }\n"
	"\n"
	"            updateFirmwareBtn.disabled = true;\n"
	"            updateFirmwareBtn.textContent = 'Updating...';\n"
	"\n"
	"            let progress = 0;\n"
	"            const interval = setInterval(() => {\n"
	"                progress += Math.random() * 10;\n"
	"                if (progress >= 100) {\n"
	"                    progress = 100;\n"
	"                    clearInterval(interval);\n"
	"                    setTimeout(() => {\n"
	"                        updateFirmwareBtn.disabled = false;\n"
	"                        updateFirmwareBtn.textContent = 'Update Firmware';\n"
	"                        showNotification('Firmware updated successfully', 'success');\n"
	"                    }, 500);\n"
	"                }\n"
	"                progressBar.style.width = `${progress}%`;\n"
	"            }, 200);\n"
	"        });\n"
	"\n"
	"        saveConfigBtn.addEventListener('click', () => {\n"
	"            const config = {\n"
	"                ssid: ssidInput.value,\n"
	"                password: passwordInput.value,\n"
	"                wifiChannel: wifiChannelSelect.value,\n"
	"                mqttEnable: mqttEnableSelect.value,\n"
	"                mqttBroker: mqttBrokerInput.value,\n"
	"                mqttUsername: mqttUsernameInput.value,\n"
	"                mqttPassword: mqttPasswordInput.value,\n"
	"                displayLayout: displayLayoutSelect.value,\n"
	"                displayParam: displayParamInput.value,\n"
	"                displayRotation: displayRotationSelect.value,\n"
	"                displayTimeout: displayTimeoutSelect.value,\n"
	"                displayContrast: displayContrastSlider.value,\n"
	"                sensorType: sensorTypeSelect.value,\n"
	"                sensorUnit: sensorUnitSelect.value,\n"
	"                ledIntensity: ledIntensitySlider.value\n"
	"            };\n"
	"\n"
	"\n"
	"            saveConfigBtn.textContent = 'Saving...';\n"
	"            setTimeout(() => {\n"
	"                saveConfigBtn.textContent = 'Save Configuration';\n"
	"                showNotification('Configuration saved successfully', 'success');\n"
	"            }, 1000);\n"
	"\n"
	"\n"
	"        });\n"
	"\n"
	"        resetDeviceBtn.addEventListener('click', () => {\n"
	"            resetDeviceBtn.textContent = 'Resetting...';\n"
	"            setTimeout(() => {\n"
	"                resetDeviceBtn.textContent = 'Reset Device';\n"
	"                showNotification('Device reset completed', 'success');\n"
	"            }, 3000);\n"
	"        });\n"
	"\n"
	"        function showNotification(message, type = 'success') {\n"
	"            notification.textContent = message;\n"
	"            notification.className = `notification ${type} show`;\n"
	"            setTimeout(() => {\n"
	"                notification.classList.remove('show');\n"
	"            }, 3000);\n"
	"        }\n"
	"\n"
	"        window.addEventListener('DOMContentLoaded', initializeForm);\n"
	"    </script>\n"
	"</body>\n"
	"</html>\n"
	"";
