/*
 * ==============================================================================
 *
 *  PROJECT:     "Rase" Radio Sensor Project,    ESP32-S3 Station Device Firmware
 *  COPYRIGHT:   (C)2025-2026 KKS-Elektronik,  M. Kreck, <makreck@googlemail.com>
 *
 *  This program is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation, either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful,   but WITHOUT
 *  ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE, see the GNU General Public License for details.
 *
 *  You should have received a copy of the  GNU General Public License along with
 *  this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * ==============================================================================
 */

#include "includes.hpp"
#include "app.hpp"

const char *WebServer::firmware_update_resp_str =
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"    <meta charset=\"UTF-8\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
	"    <title>RASE Firmware Uploader</title>\n"
	"    <style>\n"
	"        * {\n"
	"            box-sizing: border-box;\n"
	"            margin: 0;\n"
	"            padding: 0;\n"
	"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
	"        }\n"
	"\n"
	"        body {\n"
	"            background: linear-gradient(135deg, #1a2a6c, #b21f1f, #1a2a6c);\n"
	"            color: white;\n"
	"            min-height: 100vh;\n"
	"            padding: 20px;\n"
	"        }\n"
	"\n"
	"        .container {\n"
	"            max-width: 1000px;\n"
	"            margin: 0 auto;\n"
	"            padding: 20px;\n"
	"        }\n"
	"\n"
	"        header {\n"
	"            text-align: center;\n"
	"            margin-bottom: 30px;\n"
	"            padding: 20px;\n"
	"            background: rgba(0, 0, 0, 0.3);\n"
	"            border-radius: 15px;\n"
	"            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);\n"
	"        }\n"
	"\n"
	"        h1 {\n"
	"            font-size: 2.5rem;\n"
	"            margin-bottom: 10px;\n"
	"            text-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);\n"
	"        }\n"
	"\n"
	"        .subtitle {\n"
	"            font-size: 1.2rem;\n"
	"            opacity: 0.9;\n"
	"        }\n"
	"\n"
	"        .card {\n"
	"            background: rgba(255, 255, 255, 0.1);\n"
	"            backdrop-filter: blur(10px);\n"
	"            border-radius: 15px;\n"
	"            padding: 25px;\n"
	"            margin-bottom: 30px;\n"
	"            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);\n"
	"            border: 1px solid rgba(255, 255, 255, 0.18);\n"
	"        }\n"
	"\n"
	"        .card-title {\n"
	"            font-size: 1.5rem;\n"
	"            margin-bottom: 20px;\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            gap: 10px;\n"
	"        }\n"
	"\n"
	"        .card-title i {\n"
	"            font-size: 1.8rem;\n"
	"        }\n"
	"\n"
	"        .upload-area {\n"
	"            border: 3px dashed rgba(255, 255, 255, 0.3);\n"
	"            border-radius: 10px;\n"
	"            padding: 40px 20px;\n"
	"            text-align: center;\n"
	"            cursor: pointer;\n"
	"            transition: all 0.3s ease;\n"
	"            margin-bottom: 25px;\n"
	"        }\n"
	"\n"
	"        .upload-area:hover {\n"
	"            background: rgba(255, 255, 255, 0.1);\n"
	"            border-color: rgba(255, 255, 255, 0.5);\n"
	"        }\n"
	"\n"
	"        .upload-area i {\n"
	"            font-size: 3rem;\n"
	"            margin-bottom: 15px;\n"
	"            display: block;\n"
	"        }\n"
	"\n"
	"        .file-input {\n"
	"            display: none;\n"
	"        }\n"
	"\n"
	"        .btn {\n"
	"            background: linear-gradient(to right, #4A00E0, #8E2DE2);\n"
	"            color: white;\n"
	"            border: none;\n"
	"            padding: 12px 25px;\n"
	"            font-size: 1.1rem;\n"
	"            border-radius: 50px;\n"
	"            cursor: pointer;\n"
	"            transition: all 0.3s ease;\n"
	"            display: inline-block;\n"
	"            margin: 10px 5px;\n"
	"            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);\n"
	"        }\n"
	"\n"
	"        .btn:hover {\n"
	"            transform: translateY(-3px);\n"
	"            box-shadow: 0 6px 20px rgba(0, 0, 0, 0.3);\n"
	"        }\n"
	"\n"
	"        .btn:active {\n"
	"            transform: translateY(1px);\n"
	"        }\n"
	"\n"
	"        .btn:disabled {\n"
	"            background: #555;\n"
	"            cursor: not-allowed;\n"
	"            transform: none;\n"
	"            box-shadow: none;\n"
	"        }\n"
	"\n"
	"        .device-info {\n"
	"            display: grid;\n"
	"            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n"
	"            gap: 15px;\n"
	"            margin-top: 20px;\n"
	"        }\n"
	"\n"
	"        .info-item {\n"
	"            background: rgba(0, 0, 0, 0.2);\n"
	"            padding: 15px;\n"
	"            border-radius: 10px;\n"
	"        }\n"
	"\n"
	"        .info-label {\n"
	"            font-size: 0.9rem;\n"
	"            opacity: 0.8;\n"
	"            margin-bottom: 5px;\n"
	"        }\n"
	"\n"
	"        .info-value {\n"
	"            font-size: 1.1rem;\n"
	"            font-weight: bold;\n"
	"        }\n"
	"\n"
	"        .progress-container {\n"
	"            margin-top: 20px;\n"
	"            display: none;\n"
	"        }\n"
	"\n"
	"        .progress-bar {\n"
	"            height: 10px;\n"
	"            background: rgba(255, 255, 255, 0.1);\n"
	"            border-radius: 5px;\n"
	"            overflow: hidden;\n"
	"        }\n"
	"\n"
	"        .progress {\n"
	"            height: 100%;\n"
	"            background: linear-gradient(to right, #00b09b, #96c93d);\n"
	"            width: 0%;\n"
	"            transition: width 0.4s ease;\n"
	"        }\n"
	"\n"
	"        .status {\n"
	"            margin-top: 15px;\n"
	"            text-align: center;\n"
	"            min-height: 24px;\n"
	"        }\n"
	"\n"
	"        .success {\n"
	"            color: #96c93d;\n"
	"        }\n"
	"\n"
	"        .error {\n"
	"            color: #ff6b6b;\n"
	"        }\n"
	"\n"
	"        .device-id {\n"
	"            font-size: 1.8rem;\n"
	"            text-align: center;\n"
	"            margin: 20px 0;\n"
	"            padding: 15px;\n"
	"            background: rgba(0, 0, 0, 0.2);\n"
	"            border-radius: 10px;\n"
	"            word-break: break-all;\n"
	"        }\n"
	"\n"
	"        .notification {\n"
	"            position: fixed;\n"
	"            top: 20px;\n"
	"            right: 20px;\n"
	"            padding: 15px 25px;\n"
	"            border-radius: 10px;\n"
	"            background: rgba(0, 0, 0, 0.8);\n"
	"            color: white;\n"
	"            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);\n"
	"            transform: translateX(200%);\n"
	"            transition: transform 0.3s ease;\n"
	"            z-index: 1000;\n"
	"        }\n"
	"\n"
	"        .notification.show {\n"
	"            transform: translateX(0);\n"
	"        }\n"
	"\n"
	"        @media (max-width: 768px) {\n"
	"            .container {\n"
	"                padding: 10px;\n"
	"            }\n"
	"\n"
	"            h1 {\n"
	"                font-size: 2rem;\n"
	"            }\n"
	"\n"
	"            .card {\n"
	"                padding: 15px;\n"
	"            }\n"
	"        }\n"
	"    </style>\n"
	"</head>\n"
	"\n"
	"<body>\n"
	"    <div class=\"container\">\n"
	"        <header>\n"
	"            <h1>RASE Firmware Uploader</h1>\n"
	"            <p class=\"subtitle\">Securely update firmware on your devices</p>\n"
	"        </header>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\">Device Information</h2>\n"
	"            <div class=\"device-id\" id=\"deviceId\">Retrieving device ID...</div>\n"
	"\n"
	"            <div class=\"device-info\" id=\"deviceInfo\">\n"
	"                <!-- Device info will be populated here -->\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\">Firmware Update</h2>\n"
	"            <p>Select a firmware image file to upload:</p>\n"
	"\n"
	"            <div class=\"upload-area\" id=\"dropArea\">\n"
	"                <i>📁</i>\n"
	"                <p>Drag & drop your firmware file here</p>\n"
	"                <p>or</p>\n"
	"                <button class=\"btn\" id=\"browseBtn\">Browse Files</button>\n"
	"                <input type=\"file\" id=\"fileInput\" class=\"file-input\" accept=\".bin,.hex,.img\">\n"
	"            </div>\n"
	"\n"
	"            <div class=\"progress-container\" id=\"progressContainer\">\n"
	"                <div class=\"progress-bar\">\n"
	"                    <div class=\"progress\" id=\"progress\"></div>\n"
	"                </div>\n"
	"                <div class=\"status\" id=\"status\">Uploading firmware...</div>\n"
	"            </div>\n"
	"\n"
	"            <div class=\"actions\">\n"
	"                <button class=\"btn\" id=\"uploadBtn\" disabled>Upload Firmware</button>\n"
	"                <button class=\"btn\" id=\"refreshBtn\">Refresh Device Info</button>\n"
	"            </div>\n"
	"        </div>\n"
	"    </div>\n"
	"\n"
	"    <div class=\"notification\" id=\"notification\"></div>\n"
	"\n"
	"    <script>\n"
	"        document.addEventListener('DOMContentLoaded', function () {\n"
	"            const dropArea = document.getElementById('dropArea');\n"
	"            const fileInput = document.getElementById('fileInput');\n"
	"            const browseBtn = document.getElementById('browseBtn');\n"
	"            const uploadBtn = document.getElementById('uploadBtn');\n"
	"            const refreshBtn = document.getElementById('refreshBtn');\n"
	"            const progressContainer = document.getElementById('progressContainer');\n"
	"            const progress = document.getElementById('progress');\n"
	"            const status = document.getElementById('status');\n"
	"            const deviceId = document.getElementById('deviceId');\n"
	"            const deviceInfo = document.getElementById('deviceInfo');\n"
	"            const notification = document.getElementById('notification');\n"
	"\n"
	"            let selectedFile = null;\n"
	"\n"
	"            browseBtn.addEventListener('click', () => fileInput.click());\n"
	"            fileInput.addEventListener('change', handleFileSelect);\n"
	"            uploadBtn.addEventListener('click', uploadFirmware);\n"
	"            refreshBtn.addEventListener('click', fetchDeviceInfo);\n"
	"\n"
	"            ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {\n"
	"                dropArea.addEventListener(eventName, preventDefaults, false);\n"
	"            });\n"
	"\n"
	"            function preventDefaults(e) {\n"
	"                e.preventDefault();\n"
	"                e.stopPropagation();\n"
	"            }\n"
	"\n"
	"            ['dragenter', 'dragover'].forEach(eventName => {\n"
	"                dropArea.addEventListener(eventName, highlight, false);\n"
	"            });\n"
	"\n"
	"            ['dragleave', 'drop'].forEach(eventName => {\n"
	"                dropArea.addEventListener(eventName, unhighlight, false);\n"
	"            });\n"
	"\n"
	"            function highlight() {\n"
	"                dropArea.style.backgroundColor = 'rgba(255, 255, 255, 0.15)';\n"
	"                dropArea.style.borderColor = 'rgba(255, 255, 255, 0.7)';\n"
	"            }\n"
	"\n"
	"            function unhighlight() {\n"
	"                dropArea.style.backgroundColor = '';\n"
	"                dropArea.style.borderColor = 'rgba(255, 255, 255, 0.3)';\n"
	"            }\n"
	"\n"
	"            dropArea.addEventListener('drop', handleDrop, false);\n"
	"\n"
	"            function handleDrop(e) {\n"
	"                const dt = e.dataTransfer;\n"
	"                const files = dt.files;\n"
	"                if (files.length) {\n"
	"                    handleFiles(files);\n"
	"                }\n"
	"            }\n"
	"\n"
	"            function handleFileSelect(e) {\n"
	"                const files = e.target.files;\n"
	"                if (files.length) {\n"
	"                    handleFiles(files);\n"
	"                }\n"
	"            }\n"
	"\n"
	"            function handleFiles(files) {\n"
	"                selectedFile = files[0];\n"
	"                if (selectedFile.type !== 'application/octet-stream' && !selectedFile.name.endsWith('.bin')) {\n"
	"                    showNotification('Please select a valid firmware file (.bin)', 'error');\n"
	"                    return;\n"
	"                }\n"
	"\n"
	"                uploadBtn.disabled = false;\n"
	"                status.textContent = `Selected: ${selectedFile.name} (${formatFileSize(selectedFile.size)})`;\n"
	"            }\n"
	"\n"
	"            function formatFileSize(bytes) {\n"
	"                if (bytes === 0) return '0 Bytes';\n"
	"                const k = 1024;\n"
	"                const sizes = ['Bytes', 'KB', 'MB', 'GB'];\n"
	"                const i = Math.floor(Math.log(bytes) / Math.log(k));\n"
	"                return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];\n"
	"            }\n"
	"\n"
	"            function fetchDeviceInfo() {\n"
	"                showNotification('Fetching device information...', 'info');\n"
	"                fetch('/api/id', { method: 'GET' })\n"
	"                    .then(response => response.json())\n"
	"                    .then(data => {\n"
	"                        displayDeviceInfo(data);\n"
	"                        showNotification('Device information retrieved successfully', 'success');\n"
	"                    })\n"
	"                    .catch(error => {\n"
	"                        console.error('Error fetching device info:', error);\n"
	"                        showNotification('Failed to retrieve device information', 'error');\n"
	"                    });\n"
	"            }\n"
	"\n"
	"            function displayDeviceInfo(data) {\n"
	"                deviceId.textContent = data.identification;\n"
	"\n"
	"                deviceInfo.innerHTML = '';\n"
	"\n"
	"                Object.entries(data).forEach(([key, value]) => {\n"
	"                    const item = document.createElement('div');\n"
	"                    item.className = 'info-item';\n"
	"\n"
	"                    const label = document.createElement('div');\n"
	"                    label.className = 'info-label';\n"
	"                    label.textContent = key.replace(/_/g, ' ').replace(/\\b\\w/g, l => l.toUpperCase());\n"
	"\n"
	"                    const valueEl = document.createElement('div');\n"
	"                    valueEl.className = 'info-value';\n"
	"                    valueEl.textContent = value;\n"
	"\n"
	"                    item.appendChild(label);\n"
	"                    item.appendChild(valueEl);\n"
	"                    deviceInfo.appendChild(item);\n"
	"                });\n"
	"            }\n"
	"\n"
	"            function uploadFirmware() {\n"
	"                if (!selectedFile) {\n"
	"                    showNotification('Please select a firmware file first', 'error');\n"
	"                    return;\n"
	"                }\n"
	"\n"
	"                progressContainer.style.display = 'block';\n"
	"                status.textContent = 'Starting upload...';\n"
	"                progress.style.width = '0%';\n"
	"\n"
	"                const formData = new FormData();\n"
	"                formData.append('firmware', selectedFile);\n"
	"\n"
	"                fetch('/api/update', {\n"
	"                    method: 'PUT',\n"
	"                    body: formData\n"
	"                })\n"
	"                .then(response => {\n"
	"                    if (response.ok) {\n"
	"                        return response.text();\n"
	"                    } else {\n"
	"                        throw new Error(`HTTP error! status: ${response.status}`);\n"
	"                    }\n"
	"                })\n"
	"                .then(data => {\n"
	"                    status.textContent = 'Upload completed successfully';\n"
	"                    showNotification('Firmware uploaded successfully', 'success');\n"
	"                    progress.style.width = '100%';\n"
	"                })\n"
	"                .catch(error => {\n"
	"                    console.error('Error uploading firmware:', error);\n"
	"                    status.textContent = 'Upload failed';\n"
	"                    showNotification('Firmware upload failed', 'error');\n"
	"                    progress.style.width = '100%';\n"
	"                });\n"
	"            }\n"
	"\n"
	"            function showNotification(message, type) {\n"
	"                notification.textContent = message;\n"
	"                notification.className = 'notification ' + type;\n"
	"\n"
	"                setTimeout(() => {\n"
	"                    notification.className = 'notification';\n"
	"                }, 3000);\n"
	"            }\n"
	"\n"
	"            fetchDeviceInfo();\n"
	"        });\n"
	"    </script>\n"
	"</body>\n"
	"</html>\n"
	"";
