/*
 * ==============================================================================
 *
 *  PROJECT:     "Rase" Radio Sensor Project,    ESP32-S3 Station Device Firmware
 *  COPYRIGHT:   (C)2025-2026 KKS-Elektronik,  M. Kreck, <makreck@googlemail.com>
 *
 *  This program is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation, either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful,   but WITHOUT
 *  ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE, see the GNU General Public License for details.
 *
 *  You should have received a copy of the  GNU General Public License along with
 *  this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * ==============================================================================
 */

#include "includes.hpp"
#include "app.hpp"

const char* WebServer::firmware_update_resp_str = 
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"    <meta charset=\"UTF-8\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
	"    <title>RASE Firmware Uploader</title>\n"
	"    <style>\n"
	"        * {\n"
	"            margin: 0;\n"
	"            padding: 0;\n"
	"            box-sizing: border-box;\n"
	"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
	"        }\n"
	"\n"
	"        body {\n"
	"            background: linear-gradient(135deg, #1a2a6c, #b21f1f, #1a2a6c);\n"
	"            min-height: 100vh;\n"
	"            display: flex;\n"
	"            justify-content: center;\n"
	"            align-items: center;\n"
	"            padding: 20px;\n"
	"        }\n"
	"\n"
	"        .container {\n"
	"            background-color: rgba(255, 255, 255, 0.95);\n"
	"            border-radius: 15px;\n"
	"            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);\n"
	"            width: 100%;\n"
	"            max-width: 600px;\n"
	"            padding: 30px;\n"
	"            text-align: center;\n"
	"        }\n"
	"\n"
	"        h1 {\n"
	"            color: #1a2a6c;\n"
	"            margin-bottom: 10px;\n"
	"            font-size: 2.2rem;\n"
	"        }\n"
	"\n"
	"        .subtitle {\n"
	"            color: #555;\n"
	"            margin-bottom: 30px;\n"
	"            font-size: 1.1rem;\n"
	"        }\n"
	"\n"
	"        .upload-container {\n"
	"            border: 3px dashed #1a2a6c;\n"
	"            border-radius: 10px;\n"
	"            padding: 40px 20px;\n"
	"            margin: 30px 0;\n"
	"            background-color: #f8f9fa;\n"
	"            transition: all 0.3s ease;\n"
	"            cursor: pointer;\n"
	"        }\n"
	"\n"
	"        .upload-container:hover {\n"
	"            background-color: #e9ecef;\n"
	"            border-color: #b21f1f;\n"
	"        }\n"
	"\n"
	"        .upload-container.drag-over {\n"
	"            background-color: #d1ecff;\n"
	"            border-color: #0d6efd;\n"
	"        }\n"
	"\n"
	"        .upload-icon {\n"
	"            font-size: 4rem;\n"
	"            color: #1a2a6c;\n"
	"            margin-bottom: 20px;\n"
	"        }\n"
	"\n"
	"        .upload-text {\n"
	"            font-size: 1.2rem;\n"
	"            color: #333;\n"
	"            margin-bottom: 15px;\n"
	"        }\n"
	"\n"
	"        .file-info {\n"
	"            margin-top: 20px;\n"
	"            padding: 15px;\n"
	"            background-color: #e9f7fe;\n"
	"            border-radius: 8px;\n"
	"            display: none;\n"
	"        }\n"
	"\n"
	"        .file-name {\n"
	"            font-weight: bold;\n"
	"            color: #1a2a6c;\n"
	"        }\n"
	"\n"
	"        .file-size {\n"
	"            color: #666;\n"
	"            font-size: 0.9rem;\n"
	"        }\n"
	"\n"
	"        .btn {\n"
	"            background: linear-gradient(to right, #1a2a6c, #b21f1f);\n"
	"            color: white;\n"
	"            border: none;\n"
	"            padding: 15px 30px;\n"
	"            font-size: 1.1rem;\n"
	"            border-radius: 50px;\n"
	"            cursor: pointer;\n"
	"            transition: all 0.3s ease;\n"
	"            margin: 20px 0;\n"
	"            width: 100%;\n"
	"            max-width: 300px;\n"
	"            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);\n"
	"        }\n"
	"\n"
	"        .btn:hover {\n"
	"            transform: translateY(-3px);\n"
	"            box-shadow: 0 6px 20px rgba(0, 0, 0, 0.25);\n"
	"        }\n"
	"\n"
	"        .btn:disabled {\n"
	"            background: #cccccc;\n"
	"            cursor: not-allowed;\n"
	"            transform: none;\n"
	"            box-shadow: none;\n"
	"        }\n"
	"\n"
	"        .progress-container {\n"
	"            margin: 30px 0;\n"
	"            display: none;\n"
	"        }\n"
	"\n"
	"        .progress-bar {\n"
	"            height: 20px;\n"
	"            background-color: #e0e0e0;\n"
	"            border-radius: 10px;\n"
	"            overflow: hidden;\n"
	"            margin-bottom: 10px;\n"
	"        }\n"
	"\n"
	"        .progress-fill {\n"
	"            height: 100%;\n"
	"            background: linear-gradient(to right, #1a2a6c, #b21f1f);\n"
	"            width: 0%;\n"
	"            transition: width 0.4s ease;\n"
	"        }\n"
	"\n"
	"        .status-message {\n"
	"            margin-top: 15px;\n"
	"            font-size: 1rem;\n"
	"            min-height: 24px;\n"
	"        }\n"
	"\n"
	"        .success {\n"
	"            color: #28a745;\n"
	"            font-weight: bold;\n"
	"        }\n"
	"\n"
	"        .error {\n"
	"            color: #dc3545;\n"
	"            font-weight: bold;\n"
	"        }\n"
	"\n"
	"        .device-info {\n"
	"            background-color: #f0f8ff;\n"
	"            border-radius: 10px;\n"
	"            padding: 20px;\n"
	"            margin-top: 20px;\n"
	"            text-align: left;\n"
	"        }\n"
	"\n"
	"        .device-info h3 {\n"
	"            color: #1a2a6c;\n"
	"            margin-bottom: 15px;\n"
	"        }\n"
	"\n"
	"        .device-info p {\n"
	"            margin: 8px 0;\n"
	"            color: #444;\n"
	"        }\n"
	"\n"
	"        .device-id {\n"
	"            font-weight: bold;\n"
	"            color: #b21f1f;\n"
	"        }\n"
	"\n"
	"        @media (max-width: 600px) {\n"
	"            .container {\n"
	"                padding: 20px;\n"
	"            }\n"
	"\n"
	"            h1 {\n"
	"                font-size: 1.8rem;\n"
	"            }\n"
	"        }\n"
	"    </style>\n"
	"</head>\n"
	"\n"
	"<body>\n"
	"    <div class=\"container\">\n"
	"        <h1>RASE Firmware Uploader</h1>\n"
	"        <p class=\"subtitle\">Upload firmware images to your IoT device</p>\n"
	"\n"
	"        <div class=\"device-info\">\n"
	"            <h3>Device Information</h3>\n"
	"            <p><strong>Device ID:</strong> <span class=\"device-id\">ESP32-487293012</span></p>\n"
	"            <p><strong>Current Firmware:</strong> v2.1.4</p>\n"
	"            <p><strong>Status:</strong> <span style=\"color: #28a745;\">Connected</span></p>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"upload-container\" id=\"dropArea\">\n"
	"            <div class=\"upload-icon\">📁</div>\n"
	"            <p class=\"upload-text\">Drag & drop your firmware file here</p>\n"
	"            <p>or</p>\n"
	"            <button class=\"btn\" id=\"browseBtn\">Select Firmware File</button>\n"
	"            <input type=\"file\" id=\"fileInput\" accept=\".bin,.hex,.img\" style=\"display: none;\">\n"
	"        </div>\n"
	"\n"
	"        <div class=\"file-info\" id=\"fileInfo\">\n"
	"            <p>Selected file: <span class=\"file-name\" id=\"fileName\">-</span></p>\n"
	"            <p>Size: <span class=\"file-size\" id=\"fileSize\">-</span></p>\n"
	"        </div>\n"
	"\n"
	"        <button class=\"btn\" id=\"uploadBtn\" disabled>Upload Firmware</button>\n"
	"\n"
	"        <div class=\"progress-container\" id=\"progressContainer\">\n"
	"            <div class=\"progress-bar\">\n"
	"                <div class=\"progress-fill\" id=\"progressFill\"></div>\n"
	"            </div>\n"
	"            <p class=\"status-message\" id=\"statusMessage\">Preparing upload...</p>\n"
	"        </div>\n"
	"    </div>\n"
	"\n"
	"    <script>\n"
	"        document.addEventListener('DOMContentLoaded', function () {\n"
	"            const dropArea = document.getElementById('dropArea');\n"
	"            const fileInput = document.getElementById('fileInput');\n"
	"            const browseBtn = document.getElementById('browseBtn');\n"
	"            const uploadBtn = document.getElementById('uploadBtn');\n"
	"            const fileInfo = document.getElementById('fileInfo');\n"
	"            const fileName = document.getElementById('fileName');\n"
	"            const fileSize = document.getElementById('fileSize');\n"
	"            const progressContainer = document.getElementById('progressContainer');\n"
	"            const progressFill = document.getElementById('progressFill');\n"
	"            const statusMessage = document.getElementById('statusMessage');\n"
	"\n"
	"            let selectedFile = null;\n"
	"\n"
	"            browseBtn.addEventListener('click', () => {\n"
	"                fileInput.click();\n"
	"            });\n"
	"\n"
	"            fileInput.addEventListener('change', function () {\n"
	"                if (this.files && this.files[0]) {\n"
	"                    handleFile(this.files[0]);\n"
	"                }\n"
	"            });\n"
	"\n"
	"            ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {\n"
	"                dropArea.addEventListener(eventName, preventDefaults, false);\n"
	"            });\n"
	"\n"
	"            function preventDefaults(e) {\n"
	"                e.preventDefault();\n"
	"                e.stopPropagation();\n"
	"            }\n"
	"\n"
	"            ['dragenter', 'dragover'].forEach(eventName => {\n"
	"                dropArea.addEventListener(eventName, highlight, false);\n"
	"            });\n"
	"\n"
	"            ['dragleave', 'drop'].forEach(eventName => {\n"
	"                dropArea.addEventListener(eventName, unhighlight, false);\n"
	"            });\n"
	"\n"
	"            function highlight() {\n"
	"                dropArea.classList.add('drag-over');\n"
	"            }\n"
	"\n"
	"            function unhighlight() {\n"
	"                dropArea.classList.remove('drag-over');\n"
	"            }\n"
	"\n"
	"            dropArea.addEventListener('drop', handleDrop, false);\n"
	"\n"
	"            function handleDrop(e) {\n"
	"                const dt = e.dataTransfer;\n"
	"                const files = dt.files;\n"
	"\n"
	"                if (files && files[0]) {\n"
	"                    handleFile(files[0]);\n"
	"                }\n"
	"            }\n"
	"\n"
	"            function handleFile(file) {\n"
	"                selectedFile = file;\n"
	"\n"
	"                fileName.textContent = file.name;\n"
	"                fileSize.textContent = formatFileSize(file.size);\n"
	"                fileInfo.style.display = 'block';\n"
	"\n"
	"                uploadBtn.disabled = false;\n"
	"\n"
	"                progressContainer.style.display = 'none';\n"
	"            }\n"
	"\n"
	"            function formatFileSize(bytes) {\n"
	"                if (bytes === 0) return '0 Bytes';\n"
	"                const k = 1024;\n"
	"                const sizes = ['Bytes', 'KB', 'MB', 'GB'];\n"
	"                const i = Math.floor(Math.log(bytes) / Math.log(k));\n"
	"                return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];\n"
	"            }\n"
	"\n"
	"            uploadBtn.addEventListener('click', function () {\n"
	"                if (!selectedFile) return;\n"
	"\n"
	"                progressContainer.style.display = 'block';\n"
	"                statusMessage.textContent = 'Starting upload...';\n"
	"                progressFill.style.width = '0%';\n"
	"\n"
	"                let progress = 0;\n"
	"                const interval = setInterval(() => {\n"
	"                    progress += Math.random() * 10;\n"
	"                    if (progress >= 100) {\n"
	"                        progress = 100;\n"
	"                        clearInterval(interval);\n"
	"\n"
	"                        setTimeout(() => {\n"
	"                            statusMessage.textContent = 'Upload completed successfully!';\n"
	"                            statusMessage.className = 'status-message success';\n"
	"\n"
	"                            setTimeout(() => {\n"
	"                                alert('Firmware update initiated on device. Please wait for the device to restart.');\n"
	"                            }, 1000);\n"
	"                        }, 500);\n"
	"                    }\n"
	"\n"
	"                    progressFill.style.width = `${progress}%`;\n"
	"                    statusMessage.textContent = `Uploading... ${Math.round(progress)}%`;\n"
	"                }, 200);\n"
	"            });\n"
	"\n"
	"            setTimeout(() => {\n"
	"                document.querySelector('.status-message').textContent = 'Device ready for firmware update';\n"
	"                document.querySelector('.status-message').className = 'status-message success';\n"
	"            }, 1500);\n"
	"        });\n"
	"    </script>\n"
	"</body>\n"
	"</html>\n"
	"";
