/*
 * ==============================================================================
 *
 *  PROJECT:     "Rase" Radio Sensor Project,    ESP32-S3 Station Device Firmware
 *  COPYRIGHT:   (C)2025-2026 KKS-Elektronik,  M. Kreck, <makreck@googlemail.com>
 *
 *  This program is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation, either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful,   but WITHOUT
 *  ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE, see the GNU General Public License for details.
 *
 *  You should have received a copy of the  GNU General Public License along with
 *  this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * ==============================================================================
 */

#include "includes.hpp"
#include "app.hpp"

const char* WebServer::webserver_resp_str = 
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"    <meta charset=\"UTF-8\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
	"    <title>Sensor Dashboard</title>\n"
	"    <style>\n"
	"        :root {\n"
	"            --bg-gradient-1: #0f0c29;\n"
	"            --bg-gradient-2: #302b63;\n"
	"            --bg-gradient-3: #24243e;\n"
	"            --card-bg: rgba(255, 255, 255, 0.05);\n"
	"            --card-border: rgba(255, 255, 255, 0.1);\n"
	"            --text-primary: #ffffff;\n"
	"            --text-secondary: #a0a0a0;\n"
	"            --accent-color: #00d2ff;\n"
	"            --font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;\n"
	"            --font-mono: 'Courier New', Courier, monospace;\n"
	"        }\n"
	"\n"
	"        * {\n"
	"            box-sizing: border-box;\n"
	"            margin: 0;\n"
	"            padding: 0;\n"
	"        }\n"
	"\n"
	"        body {\n"
	"            font-family: var(--font-family);\n"
	"            color: var(--text-primary);\n"
	"            min-height: 100vh;\n"
	"            overflow-x: hidden;\n"
	"            background: linear-gradient(-45deg, #020103, #232141, #03030c, #121141);\n"
	"            background-size: 400% 400%;\n"
	"            padding: 20px;\n"
	"        }\n"
	"\n"
	"        .container {\n"
	"            max-width: 1200px;\n"
	"            margin: 0 auto;\n"
	"            padding-bottom: 40px;\n"
	"        }\n"
	"\n"
	"        header {\n"
	"            text-align: center;\n"
	"            margin-bottom: 30px;\n"
	"            padding: 20px;\n"
	"        }\n"
	"\n"
	"        h1 {\n"
	"            font-weight: 300;\n"
	"            font-size: 2rem;\n"
	"            letter-spacing: 2px;\n"
	"            /*text-transform: uppercase;*/\n"
	"            margin-bottom: 5px;\n"
	"            text-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);\n"
	"        }\n"
	"\n"
	"        .status-badge {\n"
	"            display: inline-block;\n"
	"            font-size: 0.8rem;\n"
	"            color: #161494;\n"
	"            background: rgba(74, 222, 128, 0.1);\n"
	"            padding: 4px 12px;\n"
	"            border-radius: 20px;\n"
	"            border: 1px solid rgba(74, 222, 128, 0.3);\n"
	"        }\n"
	"\n"
	"        .status-badge.disconnected {\n"
	"            color: #380c0c;\n"
	"            background: rgba(248, 113, 113, 0.1);\n"
	"            border-color: rgba(248, 113, 113, 0.3);\n"
	"        }\n"
	"\n"
	"        .dashboard-grid {\n"
	"            display: grid;\n"
	"            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\n"
	"            gap: 20px;\n"
	"        }\n"
	"\n"
	"        .stat-value {\n"
	"            font-family: var(--font-mono);\n"
	"            font-size: 1.0rem;\n"
	"            font-weight: 300;\n"
	"            margin-bottom: 5px;\n"
	"            color: var(--text-primary);\n"
	"        }\n"
	"\n"
	"        .card {\n"
	"            background: var(--card-bg);\n"
	"            backdrop-filter: blur(8px);\n"
	"            -webkit-backdrop-filter: blur(8px);\n"
	"            border: 1px solid var(--card-border);\n"
	"            border-radius: 16px;\n"
	"            padding: 20px;\n"
	"            transition: transform 0.3s ease, box-shadow 0.3s ease;\n"
	"            position: relative;\n"
	"            overflow: hidden;\n"
	"            display: flex;\n"
	"            flex-direction: column;\n"
	"        }\n"
	"\n"
	"        .card:hover {\n"
	"            transform: translateY(-5px);\n"
	"            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);\n"
	"            border-color: rgba(255, 255, 255, 0.2);\n"
	"        }\n"
	"\n"
	"        .card-header {\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            margin-bottom: 15px;\n"
	"        }\n"
	"\n"
	"        .icon-box {\n"
	"            width: 40px;\n"
	"            height: 40px;\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            justify-content: center;\n"
	"            background: rgba(255, 255, 255, 0.1);\n"
	"            border-radius: 10px;\n"
	"            margin-right: 12px;\n"
	"        }\n"
	"\n"
	"        .card-title {\n"
	"            font-size: 1rem;\n"
	"            color: var(--text-secondary);\n"
	"            font-weight: 500;\n"
	"        }\n"
	"\n"
	"        .card-value {\n"
	"            font-family: var(--font-mono);\n"
	"            font-size: 2.2rem;\n"
	"            font-weight: 700;\n"
	"            margin-bottom: 5px;\n"
	"            color: var(--text-primary);\n"
	"        }\n"
	"\n"
	"        .card-unit {\n"
	"            font-size: 1rem;\n"
	"            color: var(--text-secondary);\n"
	"            font-weight: 500;\n"
	"            margin-left: 5px;\n"
	"        }\n"
	"\n"
	"        .card-stats {\n"
	"            display: flex;\n"
	"            justify-content: space-between;\n"
	"            margin-top: auto;\n"
	"            padding-top: 15px;\n"
	"            border-top: 1px solid rgba(255, 255, 255, 0.05);\n"
	"            font-size: 0.8rem;\n"
	"            color: var(--text-secondary);\n"
	"        }\n"
	"\n"
	"        .stat-item span {\n"
	"            display: block;\n"
	"            color: var(--text-secondary);\n"
	"        }\n"
	"\n"
	"        .stat-item strong {\n"
	"            color: var(--text-primary);\n"
	"        }\n"
	"\n"
	"        .chart-container {\n"
	"            margin-top: 15px;\n"
	"            width: 100%;\n"
	"            height: 80px;\n"
	"            position: relative;\n"
	"        }\n"
	"\n"
	"        canvas {\n"
	"            width: 100%;\n"
	"            height: 100%;\n"
	"            display: block;\n"
	"        }\n"
	"\n"
	"        .hidden {\n"
	"            display: none !important;\n"
	"        }\n"
	"\n"
	"        #loader {\n"
	"            text-align: center;\n"
	"            margin-top: 50px;\n"
	"            color: var(--text-secondary);\n"
	"        }\n"
	"    </style>\n"
	"</head>\n"
	"\n"
	"<body>\n"
	"\n"
	"    <div class=\"container\">\n"
	"        <header>\n"
	"            <h1 id=\"device-title\">Sensor Node</h1>\n"
	"            <div class=\"stat-value\">\n"
	"                <span>Device serial number</span>\n"
	"                <span id=\"device-serial-number\">00000000000000000000</span>\n"
	"            </div>\n"
	"            <div class=\"stat-value\">\n"
	"                <span>Query time</span>\n"
	"                <span id=\"time-stamp\">0000-00-00T00:00:00</span>\n"
	"            </div>\n"
	"            <div class=\"stat-value\">\n"
	"                <span>RSSI</span>\n"
	"                <span id=\"rssi\">-99 dBm</span>\n"
	"                <span> - </span>\n"
	"                <span>TX-Power</span>\n"
	"                <span id=\"tx_power\">+10 dBm</span>\n"
	"            </div>\n"
	"\n"
	"            <span id=\"connection-status\" class=\"status-badge\">Connected</span>\n"
	"        </header>\n"
	"\n"
	"        <main id=\"dashboard-content\" class=\"dashboard-grid\">\n"
	"            <div id=\"loader\">Initializing Dashboard...</div>\n"
	"        </main>\n"
	"    </div>\n"
	"\n"
	"    <script>\n"
	"        const API_ENDPOINT = '/api/sensors';\n"
	"        const UPDATE_INTERVAL = 10000;\n"
	"\n"
	"        const ICONS = {\n"
	"            default:      '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"/><line x1=\"3\" y1=\"12\" x2=\"21\" y2=\"12\"/><line x1=\"12\" y1=\"3\" x2=\"12\" y2=\"21\"/></svg>',\n"
	"            generic:      '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width = \"20\" height = \"20\" ><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\"></line><line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\"></line></svg>',\n"
	"            percent:      '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"/><line x1=\"3\" y1=\"12\" x2=\"21\" y2=\"12\"/><line x1=\"12\" y1=\"3\" x2=\"12\" y2=\"21\"/></svg>',\n"
	"            rel_humidity: '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width = \"20\" height = \"20\" > <path d=\"M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z\"></path></svg>',\n"
	"            abs_humidity: '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"> <path d=\"M7 14c-1.1 0-2-.9-2-2 0-1.1.9-2 2-2h.06a4 4 0 0 1 7.88 0H17c1.1 0 2 .9 2 2s-.9 2-2 2H7z\" /> <path d=\"M12 16.5l-1.5 2.5h3l-1.5-2.5z\" transform=\"scale(0.6) translate(7,4)\"/></svg>',\n"
	"            air_pressure: '<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"> <circle cx=\"12\" cy=\"12\" r=\"10\" stroke=\"currentColor\" stroke-width=\"2\" fill=\"none\"/> <line x1=\"12\" y1=\"2\" x2=\"12\" y2=\"4\" stroke=\"currentColor\" stroke-width=\"1.5\"/> <line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"18\" stroke=\"currentColor\" stroke-width=\"1.5\"/> <line x1=\"10\" y1=\"8\" x2=\"12\" y2=\"8\" stroke=\"currentColor\" stroke-width=\"1\" stroke-dasharray=\"1,1\"/> <line x1=\"14\" y1=\"8\" x2=\"12\" y2=\"8\" stroke=\"currentColor\" stroke-width=\"1\" stroke-dasharray=\"1,1\"/> <line x1=\"10\" y1=\"12\" x2=\"12\" y2=\"12\" stroke=\"currentColor\" stroke-width=\"1\" stroke-dasharray=\"1,1\"/> <line x1=\"14\" y1=\"12\" x2=\"12\" y2=\"12\" stroke=\"currentColor\" stroke-width=\"1\" stroke-dasharray=\"1,1\"/> <line x1=\"10\" y1=\"16\" x2=\"12\" y2=\"16\" stroke=\"currentColor\" stroke-width=\"1\" stroke-dasharray=\"1,1\"/> <line x1=\"14\" y1=\"16\" x2=\"12\" y2=\"16\" stroke=\"currentColor\" stroke-width=\"1\" stroke-dasharray=\"1,1\"/> <path d=\"M12 12 L12 6 L10 8 Z\" stroke=\"currentColor\" stroke-width=\"2\" fill=\"none\"/> <circle cx=\"12\" cy=\"12\" r=\"1.5\" stroke=\"currentColor\" stroke-width=\"1.5\" fill=\"none\"/></svg>',\n"
	"            temperature:  '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width = \"20\" height = \"20\" > <path d=\"M14 14.76V3.5a2.5 2.5 0 0 0-5 0v11.26a4.5 4.5 0 1 0 5 0z\"></path></svg>',\n"
	"            dewpoint:     '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width = \"20\" height = \"20\" > <path d=\"M9.59 4.59A2 2 0 1 1 11 8H2m10.59 11.41A2 2 0 1 0 14 16H2m15.73-8.27A2.5 2.5 0 1 1 19.5 12H2\"></path></svg>',\n"
	"            wind:         '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width = \"20\" height = \"20\" > <path d=\"M9.59 4.59A2 2 0 1 1 11 8H2m10.59 11.41A2 2 0 1 0 14 16H2m15.73-8.27A2.5 2.5 0 1 1 19.5 12H2\"></path></svg>',\n"
	"            voltage:      '<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 8v8M8 12h8\"/></svg>',\n"
	"        };\n"
	"\n"
	"        function get_SvgIcon(key) {\n"
	"            if (key.includes('temperature'))  return ICONS.temperature;\n"
	"            if (key.includes('rel_humidity')) return ICONS.rel_humidity;\n"
	"            if (key.includes('abs_humidity')) return ICONS.abs_humidity;\n"
	"            if (key.includes('dewpoint'))     return ICONS.dewpoint;\n"
	"            if (key.includes('air_pressure')) return ICONS.air_pressure;\n"
	"            if (key.includes('percent'))      return ICONS.percent;\n"
	"            return ICONS.generic;\n"
	"        }\n"
	"\n"
	"        const dashboardContent   = document.getElementById('dashboard-content');\n"
	"        const loader             = document.getElementById('loader');\n"
	"        const deviceTitle        = document.getElementById('device-title');\n"
	"        const timeStamp          = document.getElementById('time-stamp');\n"
	"        const deviceSerialNumber = document.getElementById('device-serial-number');\n"
	"        const rssi               = document.getElementById('rssi');\n"
	"        const tx_power           = document.getElementById('tx_power');\n"
	"        const connectionStatus   = document.getElementById('connection-status');\n"
	"\n"
	"        function drawChart(canvas, historyData, color, bottom, top) {\n"
	"            if (!historyData || historyData.length < 2) return;\n"
	"\n"
	"            const ctx = canvas.getContext('2d');\n"
	"            const width = canvas.width = canvas.offsetWidth;\n"
	"            const height = canvas.height = canvas.offsetHeight;\n"
	"\n"
	"            ctx.clearRect(0, 0, width, height);\n"
	"\n"
	"            const pad = 5;\n"
	"            const chartW = width - (pad * 2);\n"
	"            const chartH = height - (pad * 2);\n"
	"\n"
	"            const mapX = (index) => (index / (historyData.length - 1)) * chartW + pad;\n"
	"            const mapY = (val) => height - pad - ((val - bottom) / (top - bottom)) * chartH;\n"
	"\n"
	"            const gradient = ctx.createLinearGradient(0, 0, 0, height);\n"
	"            gradient.addColorStop(0, 'rgba(0, 210, 255, 0.5)');\n"
	"            gradient.addColorStop(1, 'rgba(0, 210, 255, 0.0)');\n"
	"\n"
	"            ctx.beginPath();\n"
	"            ctx.moveTo(mapX(0), mapY(historyData[0]));\n"
	"\n"
	"            for (let i = 1; i < historyData.length; i++) {\n"
	"                ctx.lineTo(mapX(i), mapY(historyData[i]));\n"
	"            }\n"
	"\n"
	"            ctx.lineCap = 'round';\n"
	"            ctx.lineJoin = 'round';\n"
	"            ctx.lineWidth = 2;\n"
	"            ctx.strokeStyle = color;\n"
	"            ctx.stroke();\n"
	"\n"
	"            ctx.lineTo(mapX(historyData.length - 1), height);\n"
	"            ctx.lineTo(mapX(0), height);\n"
	"            ctx.closePath();\n"
	"            ctx.fillStyle = gradient;\n"
	"            ctx.fill();\n"
	"        }\n"
	"\n"
	"        function renderDashboard(data) {\n"
	"            dashboardContent.innerHTML = '';\n"
	"\n"
	"            deviceTitle.textContent        = data.sensor;\n"
	"            timeStamp.textContent          = data.timestamp;\n"
	"            deviceSerialNumber.textContent = data.device_serial_number;\n"
	"            rssi.textContent               = data.rssi;\n"
	"            tx_power.textContent           = data.tx_power;\n"
	"\n"
	"            data.nodes.forEach(channel => {\n"
	"                const key = Object.keys(channel)[0];\n"
	"                const iconSvg  = get_SvgIcon(key);\n"
	"\n"
	"                const channelData = channel[key];\n"
	"                const name     = channelData.name;\n"
	"                const shortcut = channelData.shortcut;\n"
	"                const unit     = channelData.unit;\n"
	"                const color    = channelData.color;\n"
	"                const bottom   = channelData.bottom;\n"
	"                const top      = channelData.top;\n"
	"                const value    = channelData.value;\n"
	"                const min      = channelData.min;\n"
	"                const max      = channelData.max;\n"
	"                const average  = channelData.average;\n"
	"                const flags    = channelData.flags;\n"
	"                const count    = channelData.count;\n"
	"                const history  = channelData.history !== undefined ? channelData.history : [];\n"
	"\n"
	"                const dot_num  = flags & 0x0f;\n"
	"\n"
	"                const card = document.createElement('div');\n"
	"                card.className = 'card';\n"
	"                card.innerHTML = `\n"
	"                    <div class=\"card-header\">\n"
	"                        <div class=\"icon-box\">${iconSvg}</div>\n"
	"                        <div class=\"card-title\">${name}</div>\n"
	"                    </div>\n"
	"                    <div class=\"card-value\">\n"
	"                        ${value.toFixed(dot_num)}\n"
	"                        <span class=\"card-unit\">${unit}</span>\n"
	"                    </div>\n"
	"                    <div class=\"chart-container\">\n"
	"                        <canvas></canvas>\n"
	"                    </div>\n"
	"                    <div class=\"card-stats\">\n"
	"                        <div class=\"stat-item\">\n"
	"                            <span>Min</span>\n"
	"                            <strong>${min.toFixed(2)}</strong>\n"
	"                        </div>\n"
	"                        <div class=\"stat-item\">\n"
	"                            <span>Average</span>\n"
	"                            <strong>${average.toFixed(2)}</strong>\n"
	"                        </div>\n"
	"                        <div class=\"stat-item\">\n"
	"                            <span>Max</span>\n"
	"                            <strong>${max.toFixed(2)}</strong>\n"
	"                        </div>\n"
	"                        <div class=\"stat-item\">\n"
	"                            <span>Count</span>\n"
	"                            <strong>${count}</strong>\n"
	"                        </div>\n"
	"                    </div>\n"
	"                `;\n"
	"                dashboardContent.appendChild(card);\n"
	"\n"
	"                if (history.length > 1) {\n"
	"                    const canvas = card.querySelector('canvas');\n"
	"                    const bounds = {\n"
	"                        bottom: bottom !== null ? bottom : Math.min(...history),\n"
	"                        top: top !== null ? top : Math.max(...history)\n"
	"                    };\n"
	"                    const range = bounds.top - bounds.bottom;\n"
	"                    if (range === 0) {\n"
	"                        bounds.bottom = current - 1;\n"
	"                        bounds.top = current + 1;\n"
	"                    } else {\n"
	"                        bounds.bottom -= range * 0.1;\n"
	"                        bounds.top += range * 0.1;\n"
	"                    }\n"
	"                    drawChart(canvas, history, color, bounds.bottom, bounds.top);\n"
	"                }\n"
	"            });\n"
	"        }\n"
	"\n"
	"        async function fetchData() {\n"
	"            try {\n"
	"                const response = await fetch(API_ENDPOINT);\n"
	"                if (!response.ok) throw new Error('Network response was not ok');\n"
	"\n"
	"                const data = await response.json();\n"
	"                if (!data) throw new Error('Invalid data received');\n"
	"\n"
	"                renderDashboard(data);\n"
	"                connectionStatus.textContent = \"Connected\";\n"
	"                connectionStatus.style.backgroundColor = \"#4caf50\";\n"
	"                connectionStatus.style.color = \"white\";\n"
	"\n"
	"            } catch (error) {\n"
	"                console.error('Fetch error:', error);\n"
	"                connectionStatus.textContent = \"Offline\";\n"
	"                connectionStatus.style.backgroundColor = \"#f44336\";\n"
	"                connectionStatus.style.color = \"white\";\n"
	"\n"
	"                dashboardContent.innerHTML = `\n"
	"                    <div class=\"card\" style=\"grid-column: 1 / -1; text-align: center; justify-content: center;\">\n"
	"                        <p style=\"color: #f44336;\">Connection Error. Retrying...</p>\n"
	"                    </div>\n"
	"                `;\n"
	"            } finally {\n"
	"                loader.classList.add('hidden');\n"
	"            }\n"
	"        }\n"
	"\n"
	"        fetchData();\n"
	"        setInterval(fetchData, UPDATE_INTERVAL);\n"
	"\n"
	"    </script>\n"
	"</body>\n"
	"</html>\n"
	"";
