#include "includes.hpp"
#include "app.hpp"

const char* WebServer::config_website_resp_str = 
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"    <meta charset=\"UTF-8\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
	"    <title>ESP32-S3 Configuration</title>\n"
	"    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\n"
	"    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n"
	"    <style>\n"
	"        :root {\n"
	"            --primary: #2196F3;\n"
	"            --primary-dark: #1976D2;\n"
	"            --secondary: #4CAF50;\n"
	"            --background: #121212;\n"
	"            --surface: #1E1E1E;\n"
	"            --surface-light: #2D2D2D;\n"
	"            --text-primary: #FFFFFF;\n"
	"            --text-secondary: #B0B0B0;\n"
	"            --error: #F44336;\n"
	"            --success: #4CAF50;\n"
	"            --warning: #FF9800;\n"
	"            --border-radius: 8px;\n"
	"            --transition: all 0.3s ease;\n"
	"        }\n"
	"\n"
	"        * {\n"
	"            margin: 0;\n"
	"            padding: 0;\n"
	"            box-sizing: border-box;\n"
	"        }\n"
	"\n"
	"        body {\n"
	"            font-family: 'Roboto', sans-serif;\n"
	"            background-color: var(--background);\n"
	"            color: var(--text-primary);\n"
	"            line-height: 1.6;\n"
	"            padding: 20px;\n"
	"        }\n"
	"\n"
	"        .container {\n"
	"            max-width: 1200px;\n"
	"            margin: 0 auto;\n"
	"        }\n"
	"\n"
	"        header {\n"
	"            display: flex;\n"
	"            justify-content: space-between;\n"
	"            align-items: center;\n"
	"            padding: 20px 0;\n"
	"            border-bottom: 1px solid var(--surface-light);\n"
	"            margin-bottom: 30px;\n"
	"        }\n"
	"\n"
	"        .logo {\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            gap: 15px;\n"
	"        }\n"
	"\n"
	"        .logo i {\n"
	"            font-size: 2.5rem;\n"
	"            color: var(--primary);\n"
	"        }\n"
	"\n"
	"        .logo h1 {\n"
	"            font-weight: 500;\n"
	"            font-size: 1.8rem;\n"
	"        }\n"
	"\n"
	"        .status {\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            gap: 10px;\n"
	"            padding: 8px 16px;\n"
	"            border-radius: 20px;\n"
	"            background-color: var(--surface-light);\n"
	"            font-size: 0.9rem;\n"
	"        }\n"
	"\n"
	"        .status-indicator {\n"
	"            width: 12px;\n"
	"            height: 12px;\n"
	"            border-radius: 50%;\n"
	"            background-color: var(--success);\n"
	"        }\n"
	"\n"
	"        .card {\n"
	"            background-color: var(--surface);\n"
	"            border-radius: var(--border-radius);\n"
	"            padding: 25px;\n"
	"            margin-bottom: 25px;\n"
	"            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);\n"
	"        }\n"
	"\n"
	"        .card-title {\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            gap: 10px;\n"
	"            margin-bottom: 20px;\n"
	"            padding-bottom: 15px;\n"
	"            border-bottom: 1px solid var(--surface-light);\n"
	"            font-size: 1.3rem;\n"
	"            font-weight: 500;\n"
	"        }\n"
	"\n"
	"        .card-title i {\n"
	"            color: var(--primary);\n"
	"        }\n"
	"\n"
	"        .form-group {\n"
	"            margin-bottom: 20px;\n"
	"        }\n"
	"\n"
	"        .form-group label {\n"
	"            display: block;\n"
	"            margin-bottom: 8px;\n"
	"            font-weight: 500;\n"
	"            color: var(--text-secondary);\n"
	"        }\n"
	"\n"
	"        .form-control {\n"
	"            width: 100%;\n"
	"            padding: 12px 15px;\n"
	"            background-color: rgba(255, 255, 255, 0.08);\n"
	"            border: 1px solid var(--surface-light);\n"
	"            border-radius: var(--border-radius);\n"
	"            color: var(--text-primary);\n"
	"            font-size: 1rem;\n"
	"            transition: var(--transition);\n"
	"        }\n"
	"\n"
	"        .form-control:focus {\n"
	"            outline: none;\n"
	"            border-color: var(--primary);\n"
	"            background-color: rgba(33, 150, 243, 0.1);\n"
	"        }\n"
	"\n"
	"        .form-row {\n"
	"            display: flex;\n"
	"            gap: 20px;\n"
	"            margin-bottom: 20px;\n"
	"        }\n"
	"\n"
	"        .form-row .form-group {\n"
	"            flex: 1;\n"
	"        }\n"
	"\n"
	"        .btn {\n"
	"            padding: 12px 25px;\n"
	"            border: none;\n"
	"            border-radius: var(--border-radius);\n"
	"            font-size: 1rem;\n"
	"            font-weight: 500;\n"
	"            cursor: pointer;\n"
	"            transition: var(--transition);\n"
	"            display: inline-flex;\n"
	"            align-items: center;\n"
	"            gap: 8px;\n"
	"        }\n"
	"\n"
	"        .btn-primary {\n"
	"            background-color: var(--primary);\n"
	"            color: white;\n"
	"        }\n"
	"\n"
	"        .btn-primary:hover {\n"
	"            background-color: var(--primary-dark);\n"
	"        }\n"
	"\n"
	"        .btn-success {\n"
	"            background-color: var(--secondary);\n"
	"            color: white;\n"
	"        }\n"
	"\n"
	"        .btn-success:hover {\n"
	"            background-color: #388E3C;\n"
	"        }\n"
	"\n"
	"        .btn-outline {\n"
	"            background-color: transparent;\n"
	"            border: 1px solid var(--primary);\n"
	"            color: var(--primary);\n"
	"        }\n"
	"\n"
	"        .btn-outline:hover {\n"
	"            background-color: rgba(33, 150, 243, 0.1);\n"
	"        }\n"
	"\n"
	"        .btn-group {\n"
	"            display: flex;\n"
	"            gap: 15px;\n"
	"            margin-top: 20px;\n"
	"        }\n"
	"\n"
	"        .firmware-upload {\n"
	"            text-align: center;\n"
	"            padding: 30px;\n"
	"            border: 2px dashed var(--surface-light);\n"
	"            border-radius: var(--border-radius);\n"
	"            margin-top: 20px;\n"
	"        }\n"
	"\n"
	"        .firmware-upload i {\n"
	"            font-size: 3rem;\n"
	"            color: var(--primary);\n"
	"            margin-bottom: 15px;\n"
	"        }\n"
	"\n"
	"        .firmware-upload p {\n"
	"            margin-bottom: 20px;\n"
	"            color: var(--text-secondary);\n"
	"        }\n"
	"\n"
	"        .file-input-wrapper {\n"
	"            position: relative;\n"
	"            overflow: hidden;\n"
	"            display: inline-block;\n"
	"            width: 100%;\n"
	"        }\n"
	"\n"
	"        .file-input-wrapper input[type=file] {\n"
	"            position: absolute;\n"
	"            left: 0;\n"
	"            top: 0;\n"
	"            opacity: 0;\n"
	"            width: 100%;\n"
	"            height: 100%;\n"
	"            cursor: pointer;\n"
	"        }\n"
	"\n"
	"        .file-input-button {\n"
	"            display: inline-block;\n"
	"            padding: 12px 25px;\n"
	"            background-color: var(--surface-light);\n"
	"            border-radius: var(--border-radius);\n"
	"            cursor: pointer;\n"
	"            transition: var(--transition);\n"
	"            width: 100%;\n"
	"            text-align: center;\n"
	"        }\n"
	"\n"
	"        .file-input-button:hover {\n"
	"            background-color: #333333;\n"
	"        }\n"
	"\n"
	"        .progress-container {\n"
	"            margin-top: 20px;\n"
	"            display: none;\n"
	"        }\n"
	"\n"
	"        .progress-bar {\n"
	"            height: 8px;\n"
	"            background-color: var(--surface-light);\n"
	"            border-radius: 4px;\n"
	"            overflow: hidden;\n"
	"        }\n"
	"\n"
	"        .progress-fill {\n"
	"            height: 100%;\n"
	"            background-color: var(--primary);\n"
	"            width: 0%;\n"
	"            transition: width 0.3s ease;\n"
	"        }\n"
	"\n"
	"        .notification {\n"
	"            position: fixed;\n"
	"            top: 20px;\n"
	"            right: 20px;\n"
	"            padding: 15px 25px;\n"
	"            border-radius: var(--border-radius);\n"
	"            background-color: var(--surface);\n"
	"            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);\n"
	"            display: flex;\n"
	"            align-items: center;\n"
	"            gap: 10px;\n"
	"            transform: translateX(200%);\n"
	"            transition: transform 0.3s ease;\n"
	"            z-index: 1000;\n"
	"        }\n"
	"\n"
	"        .notification.show {\n"
	"            transform: translateX(0);\n"
	"        }\n"
	"\n"
	"        .notification i {\n"
	"            font-size: 1.2rem;\n"
	"        }\n"
	"\n"
	"        .notification.success i {\n"
	"            color: var(--success);\n"
	"        }\n"
	"\n"
	"        .notification.error i {\n"
	"            color: var(--error);\n"
	"        }\n"
	"\n"
	"        .notification.warning i {\n"
	"            color: var(--warning);\n"
	"        }\n"
	"\n"
	"        footer {\n"
	"            text-align: center;\n"
	"            padding: 20px;\n"
	"            margin-top: 30px;\n"
	"            border-top: 1px solid var(--surface-light);\n"
	"            color: var(--text-secondary);\n"
	"            font-size: 0.9rem;\n"
	"        }\n"
	"\n"
	"        @media (max-width: 768px) {\n"
	"            .form-row {\n"
	"                flex-direction: column;\n"
	"                gap: 15px;\n"
	"            }\n"
	"\n"
	"            header {\n"
	"                flex-direction: column;\n"
	"                gap: 15px;\n"
	"                text-align: center;\n"
	"            }\n"
	"\n"
	"            .btn-group {\n"
	"                flex-direction: column;\n"
	"            }\n"
	"        }\n"
	"    </style>\n"
	"</head>\n"
	"<body>\n"
	"    <div class=\"container\">\n"
	"        <header>\n"
	"            <div class=\"logo\">\n"
	"                <i class=\"fas fa-microchip\"></i>\n"
	"                <h1>ESP32-S3 Configuration</h1>\n"
	"            </div>\n"
	"            <div class=\"status\">\n"
	"                <div class=\"status-indicator\"></div>\n"
	"                <span>Connected to device</span>\n"
	"            </div>\n"
	"        </header>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\"><i class=\"fas fa-wifi\"></i> WiFi Configuration</h2>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"ssid\">WiFi Network (SSID)</label>\n"
	"                <input type=\"text\" id=\"ssid\" class=\"form-control\" placeholder=\"Enter network name\">\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"password\">Password</label>\n"
	"                <input type=\"password\" id=\"password\" class=\"form-control\" placeholder=\"Enter password\">\n"
	"            </div>\n"
	"            <div class=\"form-row\">\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"wifi_channel\">WiFi Channel</label>\n"
	"                    <select id=\"wifi_channel\" class=\"form-control\">\n"
	"                        <option value=\"1\">Channel 1</option>\n"
	"                        <option value=\"2\">Channel 2</option>\n"
	"                        <option value=\"3\">Channel 3</option>\n"
	"                        <option value=\"4\">Channel 4</option>\n"
	"                        <option value=\"5\">Channel 5</option>\n"
	"                        <option value=\"6\">Channel 6</option>\n"
	"                        <option value=\"7\">Channel 7</option>\n"
	"                        <option value=\"8\">Channel 8</option>\n"
	"                        <option value=\"9\">Channel 9</option>\n"
	"                        <option value=\"10\">Channel 10</option>\n"
	"                        <option value=\"11\">Channel 11</option>\n"
	"                    </select>\n"
	"                </div>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\"><i class=\"fas fa-server\"></i> MQTT Configuration</h2>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"mqtt_broker\">MQTT Broker IP</label>\n"
	"                <input type=\"text\" id=\"mqtt_broker\" class=\"form-control\" placeholder=\"Enter broker IP address\">\n"
	"            </div>\n"
	"            <div class=\"form-row\">\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"mqtt_username\">Username</label>\n"
	"                    <input type=\"text\" id=\"mqtt_username\" class=\"form-control\" placeholder=\"Enter username (optional)\">\n"
	"                </div>\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"mqtt_password\">Password</label>\n"
	"                    <input type=\"password\" id=\"mqtt_password\" class=\"form-control\" placeholder=\"Enter password\n"
	"(optional)\">\n"
	"                </div>\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"mqtt_enable\">MQTT Status</label>\n"
	"                <select id=\"mqtt_enable\" class=\"form-control\">\n"
	"                    <option value=\"enabled\">Enabled</option>\n"
	"                    <option value=\"disabled\">Disabled</option>\n"
	"                </select>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\"><i class=\"fas fa-tv\"></i> Display Configuration</h2>\n"
	"            <div class=\"form-row\">\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"display_layout\">Display Layout</label>\n"
	"                    <select id=\"display_layout\" class=\"form-control\">\n"
	"                        <option value=\"Value page\">Value Page</option>\n"
	"                        <option value=\"Details page\">Details Page</option>\n"
	"                        <option value=\"Info page\">Info Page</option>\n"
	"                    </select>\n"
	"                </div>\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"display_param\">Display Parameter</label>\n"
	"                    <input type=\"number\" id=\"display_param\" class=\"form-control\" min=\"0\" max=\"255\" placeholder=\"0-255\">\n"
	"                </div>\n"
	"            </div>\n"
	"            <div class=\"form-row\">\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"display_rotation\">Display Rotation</label>\n"
	"                    <select id=\"display_rotation\" class=\"form-control\">\n"
	"                        <option value=\"0°\">0°</option>\n"
	"                        <option value=\"180°\">180°</option>\n"
	"                    </select>\n"
	"                </div>\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"display_timeout\">Timeout (seconds)</label>\n"
	"                    <input type=\"number\" id=\"display_timeout\" class=\"form-control\" min=\"30\" max=\"3600\" placeholder=\"30-3600\">\n"
	"                </div>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\"><i class=\"fas fa-sliders-h\"></i> System Settings</h2>\n"
	"            <div class=\"form-row\">\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"sensor_interval\">Sensor Update Interval (seconds)</label>\n"
	"                    <input type=\"number\" id=\"sensor_interval\" class=\"form-control\" min=\"1\" max=\"3600\" placeholder=\"1-3600\">\n"
	"                </div>\n"
	"                <div class=\"form-group\">\n"
	"                    <label for=\"led_brightness\">LED Brightness</label>\n"
	"                    <input type=\"range\" id=\"led_brightness\" class=\"form-control\" min=\"0\" max=\"100\" value=\"50\">\n"
	"                    <span id=\"brightness-value\">50%</span>\n"
	"                </div>\n"
	"            </div>\n"
	"            <div class=\"form-group\">\n"
	"                <label for=\"sensor_type\">Sensor Type</label>\n"
	"                <select id=\"sensor_type\" class=\"form-control\">\n"
	"                    <option value=\"temperature\">Temperature</option>\n"
	"                    <option value=\"humidity\">Humidity</option>\n"
	"                    <option value=\"pressure\">Pressure</option>\n"
	"                    <option value=\"temperature_humidity\">Temperature & Humidity</option>\n"
	"                </select>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"card\">\n"
	"            <h2 class=\"card-title\"><i class=\"fas fa-download\"></i> Firmware Update</h2>\n"
	"            <div class=\"firmware-upload\">\n"
	"                <i class=\"fas fa-file-upload\"></i>\n"
	"                <p>Select firmware file to update device</p>\n"
	"                <div class=\"file-input-wrapper\">\n"
	"                    <div class=\"file-input-button\" id=\"fileInputButton\">Choose Firmware File</div>\n"
	"                    <input type=\"file\" id=\"firmwareFile\" accept=\".bin\">\n"
	"                </div>\n"
	"                <div class=\"progress-container\" id=\"progressContainer\">\n"
	"                    <div class=\"progress-bar\">\n"
	"                        <div class=\"progress-fill\" id=\"progressFill\"></div>\n"
	"                    </div>\n"
	"                </div>\n"
	"            </div>\n"
	"        </div>\n"
	"\n"
	"        <div class=\"btn-group\">\n"
	"            <button class=\"btn btn-primary\" id=\"saveBtn\"><i class=\"fas fa-save\"></i> Save Configuration</button>\n"
	"            <button class=\"btn btn-outline\" id=\"resetBtn\"><i class=\"fas fa-redo\"></i> Reset to Defaults</button>\n"
	"        </div>\n"
	"\n"
	"        <footer>\n"
	"            <p>ESP32-S3 Configuration Tool v1.0 | Connected to device at 192.168.1.100</p>\n"
	"        </footer>\n"
	"    </div>\n"
	"\n"
	"    <div class=\"notification\" id=\"notification\">\n"
	"        <i class=\"fas fa-check-circle\"></i>\n"
	"        <span>Configuration saved successfully!</span>\n"
	"    </div>\n"
	"\n"
	"    <script>\n"
	"        document.addEventListener('DOMContentLoaded', function() {\n"
	"            const configData = {\n"
	"                ssid: \"MyNetwork\",\n"
	"                password: \"mypassword123\",\n"
	"                wifi_channel: \"6\",\n"
	"                mqtt_broker: \"192.168.1.100\",\n"
	"                mqtt_username: \"user123\",\n"
	"                mqtt_password: \"pass456\",\n"
	"                mqtt_enable: \"enabled\",\n"
	"                display_layout: \"Value page\",\n"
	"                display_param: \"128\",\n"
	"                display_rotation: \"0°\",\n"
	"                display_timeout: \"60\",\n"
	"                sensor_interval: \"30\",\n"
	"                led_brightness: \"75\",\n"
	"                sensor_type: \"temperature_humidity\"\n"
	"            };\n"
	"\n"
	"            document.getElementById('ssid').value = configData.ssid;\n"
	"            document.getElementById('password').value = configData.password;\n"
	"            document.getElementById('wifi_channel').value = configData.wifi_channel;\n"
	"            document.getElementById('mqtt_broker').value = configData.mqtt_broker;\n"
	"            document.getElementById('mqtt_username').value = configData.mqtt_username;\n"
	"            document.getElementById('mqtt_password').value = configData.mqtt_password;\n"
	"            document.getElementById('mqtt_enable').value = configData.mqtt_enable;\n"
	"            document.getElementById('display_layout').value = configData.display_layout;\n"
	"            document.getElementById('display_param').value = configData.display_param;\n"
	"            document.getElementById('display_rotation').value = configData.display_rotation;\n"
	"            document.getElementById('display_timeout').value = configData.display_timeout;\n"
	"            document.getElementById('sensor_interval').value = configData.sensor_interval;\n"
	"            document.getElementById('led_brightness').value = configData.led_brightness;\n"
	"            document.getElementById('sensor_type').value = configData.sensor_type;\n"
	"\n"
	"            const brightnessSlider = document.getElementById('led_brightness');\n"
	"            const brightnessValue = document.getElementById('brightness-value');\n"
	"            brightnessSlider.addEventListener('input', function() {\n"
	"                brightnessValue.textContent = this.value + '%';\n"
	"            });\n"
	"\n"
	"            const fileInputButton = document.getElementById('fileInputButton');\n"
	"            const firmwareFile = document.getElementById('firmwareFile');\n"
	"\n"
	"            fileInputButton.addEventListener('click', function() {\n"
	"                firmwareFile.click();\n"
	"            });\n"
	"\n"
	"            firmwareFile.addEventListener('change', function(e) {\n"
	"                if (this.files && this.files[0]) {\n"
	"                    const fileName = this.files[0].name;\n"
	"                    fileInputButton.textContent = fileName;\n"
	"\n"
	"                    const progressContainer = document.getElementById('progressContainer');\n"
	"                    const progressFill = document.getElementById('progressFill');\n"
	"\n"
	"                    progressContainer.style.display = 'block';\n"
	"                    progressFill.style.width = '0%';\n"
	"\n"
	"                    let progress = 0;\n"
	"                    const interval = setInterval(() => {\n"
	"                        progress += 5;\n"
	"                        progressFill.style.width = progress + '%';\n"
	"\n"
	"                        if (progress >= 100) {\n"
	"                            clearInterval(interval);\n"
	"\n"
	"                            setTimeout(() => {\n"
	"                                showNotification('Firmware update completed successfully!', 'success');\n"
	"                                progressContainer.style.display = 'none';\n"
	"                                fileInputButton.textContent = 'Choose Firmware File';\n"
	"                                firmwareFile.value = '';\n"
	"                            }, 500);\n"
	"                        }\n"
	"                    }, 100);\n"
	"                }\n"
	"            });\n"
	"\n"
	"            document.getElementById('saveBtn').addEventListener('click', function() {\n"
	"                showNotification('Configuration saved successfully!', 'success');\n"
	"            });\n"
	"\n"
	"            document.getElementById('resetBtn').addEventListener('click', function() {\n"
	"                if (confirm('Are you sure you want to reset all settings to defaults?')) {\n"
	"                    showNotification('Settings reset to defaults', 'warning');\n"
	"                }\n"
	"            });\n"
	"        });\n"
	"\n"
	"        function showNotification(message, type) {\n"
	"            const notification = document.getElementById('notification');\n"
	"            const icon = notification.querySelector('i');\n"
	"            const span = notification.querySelector('span');\n"
	"\n"
	"            span.textContent = message;\n"
	"\n"
	"            if (type === 'success') {\n"
	"                icon.className = 'fas fa-check-circle';\n"
	"                notification.className = 'notification success show';\n"
	"            } else if (type === 'error') {\n"
	"                icon.className = 'fas fa-exclamation-circle';\n"
	"                notification.className = 'notification error show';\n"
	"            } else if (type === 'warning') {\n"
	"                icon.className = 'fas fa-exclamation-triangle';\n"
	"                notification.className = 'notification warning show';\n"
	"            }\n"
	"\n"
	"            setTimeout(() => {\n"
	"                notification.classList.remove('show');\n"
	"            }, 3000);\n"
	"        }\n"
	"    </script>\n"
	"</body>\n"
	"</html>\n"
	"\n"
	"";
