/*
 * ==============================================================================
 *
 *  PROJECT:     "Rase" Radio Sensor Project,    ESP32-S3 Station Device Firmware
 *  COPYRIGHT:   (C)2025-2026 KKS-Elektronik,  M. Kreck, <makreck@googlemail.com>
 *
 *  This program is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation, either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful,   but WITHOUT
 *  ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE, see the GNU General Public License for details.
 *
 *  You should have received a copy of the  GNU General Public License along with
 *  this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * ==============================================================================
 */

#include "includes.hpp"
#include "app.hpp"

const char* WebServer::config_website_resp_str =
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"    <meta charset=\"UTF-8\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
	"    <title>RASE Sensor Configuration</title>\n"
	"    <style>\n"
	"        body {\n"
	"            background-color: #2c3e50; /* dark blue-ish background */\n"
	"            color: #ecf0f1;\n"
	"            font-family: Arial, sans-serif;\n"
	"            margin: 0;\n"
	"            padding: 20px;\n"
	"            display: flex;\n"
	"            justify-content: center;\n"
	"            align-items: center;\n"
	"            height: 100vh;\n"
	"        }\n"
	"        .container {\n"
	"            background-color: rgba(255, 255, 255, 0.1);\n"
	"            border-radius: 10px;\n"
	"            padding: 30px;\n"
	"            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
	"        }\n"
	"        label {\n"
	"            display: block;\n"
	"            margin-bottom: 5px;\n"
	"            font-weight: bold;\n"
	"        }\n"
	"        input[type=\"text\"], select {\n"
	"            width: 100%;\n"
	"            padding: 10px;\n"
	"            margin-bottom: 15px;\n"
	"            border-radius: 5px;\n"
	"            border: none;\n"
	"        }\n"
	"        button {\n"
	"            background-color: #16a085; /* teal-ish button */\n"
	"            color: white;\n"
	"            padding: 10px 20px;\n"
	"            border: none;\n"
	"            border-radius: 5px;\n"
	"            cursor: pointer;\n"
	"        }\n"
	"        button:hover {\n"
	"            background-color: #1abc9c;\n"
	"        }\n"
	"    </style>\n"
	"</head>\n"
	"<body>\n"
	"\n"
	"<div class=\"container\">\n"
	"    <h1>ESP32-S3 Configuration</h1>\n"
	"\n"
	"    <div id=\"config-form\">\n"
	"        <label for=\"ssid\">SSID:</label>\n"
	"        <input type=\"text\" id=\"ssid\" name=\"ssid\"><br>\n"
	"\n"
	"        <label for=\"password\">Password:</label>\n"
	"        <input type=\"password\" id=\"password\" name=\"password\"><br>\n"
	"\n"
	"        <label for=\"wifi-channel\">WiFi Channel:</label>\n"
	"        <select id=\"wifi-channel\" name=\"wifi_channel\">\n"
	"            <option value=\"1\">1</option>\n"
	"            <option value=\"6\">6</option>\n"
	"            <option value=\"11\">11</option>\n"
	"        </select><br>\n"
	"\n"
	"        <label for=\"mqtt-broker\">MQTT Broker IP:</label>\n"
	"        <input type=\"text\" id=\"mqtt-broker\" name=\"mqtt_broker\"><br>\n"
	"\n"
	"        <label for=\"mqtt-username\">MQTT Username:</label>\n"
	"        <input type=\"text\" id=\"mqtt-username\" name=\"mqtt_username\"><br>\n"
	"\n"
	"        <label for=\"mqtt-password\">MQTT Password:</label>\n"
	"        <input type=\"password\" id=\"mqtt-password\" name=\"mqtt_password\"><br>\n"
	"\n"
	"        <label for=\"mqtt-enable\">Enable MQTT:</label>\n"
	"        <select id=\"mqtt-enable\" name=\"mqtt_enable\">\n"
	"            <option value=\"enabled\">Enabled</option>\n"
	"            <option value=\"disabled\">Disabled</option>\n"
	"        </select><br>\n"
	"\n"
	"        <label for=\"display-layout\">Display Layout:</label>\n"
	"        <select id=\"display-layout\" name=\"display_layout\">\n"
	"            <option value=\"Value page\">Value Page</option>\n"
	"            <option value=\"Details page\">Details Page</option>\n"
	"            <option value=\"Info page\">Info Page</option>\n"
	"        </select><br>\n"
	"\n"
	"        <label for=\"display-param\">Display Parameter:</label>\n"
	"        <input type=\"number\" id=\"display-param\" name=\"display_param\" min=\"0\" max=\"255\"><br>\n"
	"\n"
	"        <label for=\"display-rotation\">Display Rotation:</label>\n"
	"        <select id=\"display-rotation\" name=\"display_rotation\">\n"
	"            <option value=\"0°\">0°</option>\n"
	"            <option value=\"180°\">180°</option>\n"
	"        </select><br>\n"
	"\n"
	"        <label for=\"display-timeout\">Display Timeout:</label>\n"
	"        <select id=\"display-timeout\" name=\"display_timeout\">\n"
	"            <option value=\"Never\">Never</option>\n"
	"            <option value=\"10 s\">10 s</option>\n"
	"            <option value=\"1 min\">1 min</option>\n"
	"            <option value=\"5 min\">5 min</option>\n"
	"            <option value=\"15 min\">15 min</option>\n"
	"            <option value=\"30 min\">30 min</option>\n"
	"        </select><br>\n"
	"\n"
	"        <label for=\"display-contrast\">Display Contrast:</label>\n"
	"        <input type=\"number\" id=\"display-contrast\" name=\"display_contrast\" min=\"1\" max=\"100\"><br>\n"
	"\n"
	"        <label for=\"sensor-type\">Sensor Type:</label>\n"
	"        <select id=\"sensor-type\" name=\"sensor_type\">\n"
	"            <option value=\"BMx280\">BME280</option>\n"
	"            <option value=\"autoscan\">Auto Scan</option>\n"
	"            <option value=\"Null\">Null</option>\n"
	"            <option value=\"SHT2x\">SHT2x</option>\n"
	"            <option value=\"SHT3x\">SHT3x</option>\n"
	"            <option value=\"HTU21d\">HTU21D</option>\n"
	"            <option value=\"ATHxx\">ATH Sensor</option>\n"
	"            <option value=\"HDC1080\">HDC1080</option>\n"
	"        </select><br>\n"
	"\n"
	"        <label for=\"led-intensity\">LED Intensity:</label>\n"
	"        <input type=\"number\" id=\"led-intensity\" name=\"led_intensity\" min=\"1\" max=\"100\"><br>\n"
	"\n"
	"        <button onclick=\"fetchConfig()\">Load Configuration</button>\n"
	"        <button onclick=\"saveConfig()\">Save Configuration</button>\n"
	"    </div>\n"
	"\n"
	"    <h2>Firmware Update</h2>\n"
	"    <input type=\"file\" id=\"firmware-file\" accept=\".bin\">\n"
	"    <button onclick=\"uploadFirmware()\">Upload Firmware</button>\n"
	"</div>\n"
	"\n"
	"<script>\n"
	"function fetchConfig() {\n"
	"    fetch('/api/config')\n"
	"        .then(response => response.json())\n"
	"        .then(data => {\n"
	"            document.getElementById('ssid').value = data.ssid;\n"
	"            document.getElementById('password').value = '********'.repeat(data.password.length);\n"
	"            document.getElementById('wifi-channel').value = data.wifi_channel;\n"
	"            document.getElementById('mqtt-broker').value = data.mqtt_broker;\n"
	"            document.getElementById('mqtt-username').value = data.mqtt_username;\n"
	"            document.getElementById('mqtt-password').value = '********'.repeat(data.mqtt_password.length);\n"
	"            document.getElementById('mqtt-enable').value = data.mqtt_enable;\n"
	"            document.getElementById('display-layout').value = data.display_layout;\n"
	"            document.getElementById('display-param').value = data.display_param;\n"
	"            document.getElementById('display-rotation').value = data.display_rotation;\n"
	"            document.getElementById('display-timeout').value = data.display_timeout;\n"
	"            document.getElementById('display-contrast').value = data.display_contrast;\n"
	"            document.getElementById('sensor-type').value = data.sensor_type.split(',')[0];\n"
	"            document.getElementById('led-intensity').value = parseInt(data.led_intensity);\n"
	"        })\n"
	"        .catch(error => console.error('Error fetching config:', error));\n"
	"}\n"
	"\n"
	"function saveConfig() {\n"
	"    const formData = new FormData(document.getElementById('config-form'));\n"
	"\n"
	"    const data = {};\n"
	"    for (const [key, value] of formData.entries()) {\n"
	"        if (key === 'password') {\n"
	"            data[key] = document.getElementById(key).type === 'password' ? value : '';\n"
	"        } else if (key === 'sensor_type') {\n"
	"            data[key] = `${value},${fetchConfigData('sensor_type').split(',').join(',')}`;\n"
	"        } else {\n"
	"            data[key] = value;\n"
	"        }\n"
	"    }\n"
	"\n"
	"    fetch('/api/config', {\n"
	"        method: 'PUT',\n"
	"        headers: {\n"
	"            'Content-Type': 'application/json'\n"
	"        },\n"
	"        body: JSON.stringify(data)\n"
	"    })\n"
	"    .then(response => response.json())\n"
	"    .then(() => alert('Configuration saved successfully!'))\n"
	"    .catch(error => console.error('Error saving config:', error));\n"
	"}\n"
	"\n"
	"function uploadFirmware() {\n"
	"    const fileInput = document.getElementById('firmware-file');\n"
	"    if (fileInput.files.length === 0) {\n"
	"        alert('Please select a firmware file.');\n"
	"        return;\n"
	"    }\n"
	"\n"
	"    const file = fileInput.files[0];\n"
	"    const formData = new FormData();\n"
	"    formData.append('firmware', file);\n"
	"\n"
	"    fetch('/update', {\n"
	"        method: 'PUT',\n"
	"        body: formData\n"
	"    })\n"
	"    .then(() => alert('Firmware upload successful!'))\n"
	"    .catch(error => console.error('Error uploading firmware:', error));\n"
	"}\n"
	"\n"
	"function fetchConfigData(key) {\n"
	"    return (async () => {\n"
	"        const response = await fetch('/api/config');\n"
	"        if (!response.ok) throw new Error('Network response was not ok.');\n"
	"        const data = await response.json();\n"
	"        return data[key];\n"
	"    })();\n"
	"}\n"
	"</script>\n"
	"\n"
	"</body>\n"
	"</html>\n"
	"\n"
	"";
